<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Vistara.Api/Vistara.Api.csproj" />
    <ProjectReference Include="../../../src/Vistara.Worker/Vistara.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Vistara.E2E.HostTests" />
  </ItemGroup>
</Project>
