// <auto-generated>
// Generated by src/Vistara.Web/scripts/gallery-api.mjs from
// src/Vistara.Api/OpenApi/Gallery/gallery-contract.openapi.json.
// The manifest is a temporary reviewed contract and does not assert runtime routes exist.
// Do not edit this file directly.
// </auto-generated>

#nullable enable

using System.Collections.ObjectModel;
using Vistara.Contracts.Assets;
using Vistara.Contracts.Concurrency;
using Vistara.Contracts.Errors;
using Vistara.Contracts.Gallery;
using Vistara.Contracts.Idempotency;
using Vistara.Contracts.Lifecycle;
using Vistara.Contracts.Pagination;
using Vistara.Contracts.Sharing;

namespace Vistara.Api.OpenApi.Gallery;

public static class GalleryOpenApiCatalog
{
    private static readonly IReadOnlyDictionary<string, GalleryOpenApiOperation> ById =
        BuildCatalog();

    private static readonly IReadOnlyDictionary<Type, GalleryOpenApiSchema> ByType =
        BuildSchemas();

    public static IReadOnlyCollection<GalleryOpenApiOperation> Operations =>
        new ReadOnlyCollection<GalleryOpenApiOperation>(ById.Values.ToArray());

    public static IReadOnlyCollection<GalleryOpenApiSchema> Schemas =>
        new ReadOnlyCollection<GalleryOpenApiSchema>(ByType.Values.ToArray());

    public static Type ProblemSchema => typeof(ApiProblemDetails);

    public static GalleryOpenApiOperation Get(string operationId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(operationId);
        return ById.TryGetValue(operationId, out GalleryOpenApiOperation? operation)
            ? operation
            : throw new KeyNotFoundException(
                $"Gallery OpenAPI operation '{operationId}' is not registered.");
    }

    public static GalleryOpenApiSchema GetSchema(Type contractType)
    {
        ArgumentNullException.ThrowIfNull(contractType);
        return ByType.TryGetValue(contractType, out GalleryOpenApiSchema? schema)
            ? schema
            : throw new KeyNotFoundException(
                $"Gallery OpenAPI schema for '{contractType.Name}' is not registered.");
    }

    private static ReadOnlyDictionary<string, GalleryOpenApiOperation> BuildCatalog()
    {
        GalleryOpenApiOperation[] operations =
        [
            new(
                "listAssets",
                "GET",
                "/api/v1/assets",
                "List tenant-visible assets with opaque keyset pagination.",
                typeof(AssetListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(CursorPage<AssetSummaryResponse>))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "getAsset",
                "GET",
                "/api/v1/assets/{id}",
                "Get a tenant-visible asset and safe metadata summary.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "updateAsset",
                "PATCH",
                "/api/v1/assets/{id}",
                "Update mutable asset metadata using a strong If-Match ETag.",
                null,
                [typeof(UpdateAssetRequest)],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "getAssetMetadata",
                "GET",
                "/api/v1/assets/{id}/metadata",
                "Get permission-gated allowlisted metadata without raw metadata blocks.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetMetadataResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "bulkMutateAssets",
                "POST",
                "/api/v1/assets/bulk",
                "Queue a bounded, version-aware bulk asset mutation.",
                null,
                [typeof(AssetBulkMutationRequest)],
                [new GalleryOpenApiPayload(202, typeof(OperationJobResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "getTimeline",
                "GET",
                "/api/v1/timeline",
                "List assets grouped by capture date with import-date fallback.",
                typeof(TimelineQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(TimelinePageResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "getSearchFacets",
                "GET",
                "/api/v1/search/facets",
                "Get bounded facets for the normalized asset query.",
                typeof(AssetListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(SearchFacetsResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "listAlbums",
                "GET",
                "/api/v1/albums",
                "List albums with opaque keyset pagination.",
                typeof(AlbumListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(CursorPage<AlbumSummaryResponse>))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "createAlbum",
                "POST",
                "/api/v1/albums",
                "Create an album idempotently.",
                null,
                [typeof(CreateAlbumRequest)],
                [new GalleryOpenApiPayload(201, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "getAlbum",
                "GET",
                "/api/v1/albums/{id}",
                "Get an album and a cursor page of ordered members.",
                typeof(AlbumListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "updateAlbum",
                "PATCH",
                "/api/v1/albums/{id}",
                "Update album metadata using a strong If-Match ETag.",
                null,
                [typeof(UpdateAlbumRequest)],
                [new GalleryOpenApiPayload(200, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "deleteAlbum",
                "DELETE",
                "/api/v1/albums/{id}",
                "Delete an album without deleting its assets.",
                null,
                [],
                [new GalleryOpenApiPayload(204, null)],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "addAlbumItems",
                "POST",
                "/api/v1/albums/{id}/items",
                "Add a bounded set of versioned assets to an album.",
                null,
                [typeof(AddAlbumItemsRequest)],
                [new GalleryOpenApiPayload(200, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "removeAlbumItems",
                "DELETE",
                "/api/v1/albums/{id}/items",
                "Remove a bounded set of assets from an album.",
                null,
                [typeof(RemoveAlbumItemsRequest)],
                [new GalleryOpenApiPayload(200, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "reorderAlbumItems",
                "PATCH",
                "/api/v1/albums/{id}/items/order",
                "Replace album member positions using a strong If-Match ETag.",
                null,
                [typeof(ReorderAlbumItemsRequest)],
                [new GalleryOpenApiPayload(200, typeof(AlbumDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "listTags",
                "GET",
                "/api/v1/tags",
                "List tenant tags with opaque keyset pagination.",
                typeof(TagListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(CursorPage<TagResponse>))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "createTag",
                "POST",
                "/api/v1/tags",
                "Create a tenant tag idempotently.",
                null,
                [typeof(CreateTagRequest)],
                [new GalleryOpenApiPayload(201, typeof(TagResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "updateTag",
                "PATCH",
                "/api/v1/tags/{id}",
                "Update a tag using a strong If-Match ETag.",
                null,
                [typeof(UpdateTagRequest)],
                [new GalleryOpenApiPayload(200, typeof(TagResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "deleteTag",
                "DELETE",
                "/api/v1/tags/{id}",
                "Delete a tag without deleting tagged assets.",
                null,
                [],
                [new GalleryOpenApiPayload(204, null)],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "addAssetTag",
                "PUT",
                "/api/v1/assets/{id}/tags/{tagId}",
                "Add a tag to an asset.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "removeAssetTag",
                "DELETE",
                "/api/v1/assets/{id}/tags/{tagId}",
                "Remove a tag from an asset.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "favoriteAsset",
                "PUT",
                "/api/v1/assets/{id}/favorite",
                "Add an asset to the current user's favorites.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "unfavoriteAsset",
                "DELETE",
                "/api/v1/assets/{id}/favorite",
                "Remove an asset from the current user's favorites.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(AssetDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "listShares",
                "GET",
                "/api/v1/shares",
                "List managed share links without returning bearer tokens.",
                typeof(ShareListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(CursorPage<ShareSummaryResponse>))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "createShare",
                "POST",
                "/api/v1/shares",
                "Create a revocable share and return its bearer token once.",
                null,
                [typeof(CreateShareRequest)],
                [new GalleryOpenApiPayload(201, typeof(CreatedShareResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "getShare",
                "GET",
                "/api/v1/shares/{id}",
                "Get a managed share without returning its bearer token.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(ShareDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "updateShare",
                "PATCH",
                "/api/v1/shares/{id}",
                "Update share permissions or expiry using a strong If-Match ETag.",
                null,
                [typeof(UpdateShareRequest)],
                [new GalleryOpenApiPayload(200, typeof(ShareDetailResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "revokeShare",
                "DELETE",
                "/api/v1/shares/{id}",
                "Revoke a share using a strong If-Match ETag.",
                null,
                [],
                [new GalleryOpenApiPayload(204, null)],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "getPublicShare",
                "GET",
                "/api/v1/public/shares/{token}",
                "Get the intentionally limited public share projection.",
                typeof(CursorPageRequest),
                [],
                [new GalleryOpenApiPayload(200, typeof(PublicShareResponse))],
                Array.AsReadOnly([400, 401, 404, 410, 429, 503]),
                RequiredHeaders(false, false),
                false,
                false,
                false),
            new(
                "challengePublicShare",
                "POST",
                "/api/v1/public/shares/{token}/challenge",
                "Challenge a password-protected share and establish a short-lived session.",
                null,
                [typeof(ShareChallengeRequest)],
                [new GalleryOpenApiPayload(200, typeof(ShareChallengeResponse))],
                Array.AsReadOnly([400, 401, 404, 410, 429, 503]),
                RequiredHeaders(false, false),
                false,
                false,
                false),
            new(
                "listTrash",
                "GET",
                "/api/v1/trash",
                "List trashed assets and their retention deadlines.",
                typeof(TrashListQuery),
                [],
                [new GalleryOpenApiPayload(200, typeof(CursorPage<TrashAssetResponse>))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
            new(
                "restoreAssets",
                "POST",
                "/api/v1/trash/restore",
                "Restore a bounded set of versioned assets.",
                null,
                [typeof(RestoreAssetsRequest)],
                [new GalleryOpenApiPayload(202, typeof(OperationJobResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "dryRunPurge",
                "POST",
                "/api/v1/trash/purge",
                "Create a revision-bound purge dry run without deleting assets.",
                null,
                [typeof(CreatePurgeDryRunRequest)],
                [new GalleryOpenApiPayload(200, typeof(PurgeDryRunResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 422, 429, 503]),
                RequiredHeaders(false, true),
                true,
                false,
                true),
            new(
                "confirmPurge",
                "POST",
                "/api/v1/trash/purge/{batchId}/confirm",
                "Separately confirm a dry run before queuing permanent deletion.",
                null,
                [typeof(ConfirmPurgeRequest)],
                [new GalleryOpenApiPayload(202, typeof(PurgeBatchResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 412, 422, 428, 429, 503]),
                RequiredHeaders(true, true),
                true,
                true,
                true),
            new(
                "getPurgeStatus",
                "GET",
                "/api/v1/trash/purge/{batchId}",
                "Get purge batch progress and per-item outcomes.",
                null,
                [],
                [new GalleryOpenApiPayload(200, typeof(PurgeBatchResponse))],
                Array.AsReadOnly([400, 401, 403, 404, 409, 429, 503]),
                RequiredHeaders(false, false),
                true,
                false,
                false),
        ];

        var byId = new Dictionary<string, GalleryOpenApiOperation>(StringComparer.Ordinal);
        foreach (GalleryOpenApiOperation operation in operations)
        {
            byId.Add(operation.OperationId, operation);
        }

        return new ReadOnlyDictionary<string, GalleryOpenApiOperation>(byId);
    }

    private static ReadOnlyDictionary<Type, GalleryOpenApiSchema> BuildSchemas()
    {
        GalleryOpenApiSchema[] schemas =
        [
            new(
                "ProblemDetails",
                typeof(ApiProblemDetails),
                "RFC 9457 problem details with stable code and correlation extensions."),
            new(
                "AssetListQuery",
                typeof(AssetListQuery),
                "Opaque cursor, bounded limit, normalized search filters, and stable sorting."),
            new(
                "AssetSummary",
                typeof(AssetSummaryResponse),
                "Tenant-visible asset summary with safe metadata and application delivery paths."),
            new(
                "AssetDetail",
                typeof(AssetDetailResponse),
                "Asset summary, allowlisted metadata summary, and album memberships."),
            new(
                "AssetMetadata",
                typeof(AssetMetadataResponse),
                "Permission-gated normalized metadata without raw metadata blocks."),
            new(
                "AssetBulkMutation",
                typeof(AssetBulkMutationRequest),
                "A bounded set of versioned asset targets and one allowlisted action."),
            new(
                "TimelinePage",
                typeof(TimelinePageResponse),
                "Capture-date groups with import-date fallback and an opaque next cursor."),
            new(
                "SearchFacets",
                typeof(SearchFacetsResponse),
                "Bounded facet groups for the normalized asset query."),
            new(
                "AlbumDetail",
                typeof(AlbumDetailResponse),
                "Mutable album metadata plus an ordered cursor page of members."),
            new(
                "Tag",
                typeof(TagResponse),
                "Flat tenant tag with aggregate version."),
            new(
                "ShareDetail",
                typeof(ShareDetailResponse),
                "Managed share state without its bearer token or password material."),
            new(
                "PublicShare",
                typeof(PublicShareResponse),
                "Intentionally limited public projection with no tenant or private metadata."),
            new(
                "TrashAsset",
                typeof(TrashAssetResponse),
                "Trashed asset, retention deadline, holds, references, and reclaim estimate."),
            new(
                "PurgeDryRun",
                typeof(PurgeDryRunResponse),
                "Revision-bound purge eligibility and impact preview requiring later confirmation."),
            new(
                "PurgeBatch",
                typeof(PurgeBatchResponse),
                "Purge progress and per-item outcomes after separate human confirmation."),
        ];

        return new ReadOnlyDictionary<Type, GalleryOpenApiSchema>(
            schemas.ToDictionary(schema => schema.ClrType));
    }

    private static ReadOnlyDictionary<string, Type> RequiredHeaders(
        bool requiresIfMatch,
        bool requiresIdempotencyKey)
    {
        var headers = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
        if (requiresIfMatch)
        {
            headers.Add("If-Match", typeof(EntityTag));
        }

        if (requiresIdempotencyKey)
        {
            headers.Add("Idempotency-Key", typeof(IdempotencyKey));
        }

        return new ReadOnlyDictionary<string, Type>(headers);
    }
}
