// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Sqlite.Migrations
{
    /// <inheritdoc />
    public partial class AddUploadIngestPersistence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "activated_asset_id",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "activated_blob_id",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "activated_revision_id",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "cleanup_completed_at_utc",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "commit_idempotency_key",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "commit_request_hash",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 64,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "display_file_name",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 255,
                nullable: false,
                defaultValue: "upload");

            migrationBuilder.AddColumn<Guid>(
                name: "ingest_operation_id",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "multipart_expires_at_utc",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "multipart_max_part_bytes",
                table: "upload_sessions",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "multipart_max_parts",
                table: "upload_sessions",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "multipart_min_part_bytes",
                table: "upload_sessions",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "rejected_at_utc",
                table: "upload_sessions",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "rejection_code",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "staging_entity_tag",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "staging_provider_checksum",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 512,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "staging_provider_version",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "storage_container",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "storage_provider",
                table: "upload_sessions",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "consumed_by_operation_id",
                table: "quota_reservations",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "created_at_utc",
                table: "quota_reservations",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<string>(
                name: "idempotency_key",
                table: "quota_reservations",
                type: "TEXT",
                maxLength: 200,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "request_fingerprint",
                table: "quota_reservations",
                type: "TEXT",
                maxLength: 256,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<long>(
                name: "reserved_budget_units",
                table: "quota_reservations",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddColumn<long>(
                name: "reserved_jobs",
                table: "quota_reservations",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddColumn<long>(
                name: "reserved_uploads",
                table: "quota_reservations",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddColumn<DateTime>(
                name: "updated_at_utc",
                table: "quota_reservations",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<long>(
                name: "version",
                table: "quota_reservations",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.Sql(
                """
                UPDATE upload_sessions
                SET display_file_name = 'upload'
                WHERE display_file_name = '';

                UPDATE quota_reservations
                SET state = 'Expired'
                WHERE state = 'Reserved'
                  AND EXISTS (
                      SELECT 1
                      FROM upload_sessions AS upload
                      WHERE upload.tenant_id = quota_reservations.tenant_id
                        AND upload.id = quota_reservations.upload_session_id
                        AND upload.strategy = 'Multipart'
                        AND upload.provider_upload_id IS NOT NULL
                        AND upload.state IN (
                            'Pending',
                            'UploadIssued',
                            'OutcomeUnknown',
                            'Reconciling')
                  );

                UPDATE upload_sessions
                SET
                    last_known_state = COALESCE(last_known_state, state),
                    state = 'Expired',
                    provider_upload_id = NULL,
                    updated_at_utc = CASE
                        WHEN updated_at_utc < expires_at_utc
                            THEN expires_at_utc
                        ELSE updated_at_utc
                    END,
                    version = version + 1
                WHERE strategy = 'Multipart'
                  AND provider_upload_id IS NOT NULL
                  AND state IN (
                      'Pending',
                      'UploadIssued',
                      'OutcomeUnknown',
                      'Reconciling');

                UPDATE quota_reservations
                SET expires_at_utc = '0001-01-01T00:00:01.000Z'
                WHERE julianday(expires_at_utc) <=
                    julianday('0001-01-01T00:00:00.000Z');

                UPDATE quota_reservations
                SET
                    idempotency_key = CASE
                        WHEN upload_session_id IS NULL THEN
                            'legacy-reservation:' ||
                            lower(replace(CAST(id AS TEXT), '-', ''))
                        ELSE COALESCE(
                            (
                                SELECT CASE
                                    WHEN length(request.key) <= 160 THEN
                                        'upload:' ||
                                        lower(replace(
                                            CAST(upload.actor_id AS TEXT),
                                            '-',
                                            '')) ||
                                        ':' ||
                                        request.key
                                    ELSE
                                        'legacy-upload:' ||
                                        lower(replace(
                                            CAST(upload.actor_id AS TEXT),
                                            '-',
                                            '')) ||
                                        ':' ||
                                        lower(replace(
                                            CAST(quota_reservations.id AS TEXT),
                                            '-',
                                            ''))
                                END
                                FROM upload_sessions AS upload
                                JOIN idempotency_requests AS request
                                  ON request.tenant_id = upload.tenant_id
                                 AND request.upload_session_id = upload.id
                                WHERE upload.tenant_id =
                                    quota_reservations.tenant_id
                                  AND upload.id =
                                    quota_reservations.upload_session_id
                                LIMIT 1
                            ),
                            (
                                SELECT
                                    'legacy-upload:' ||
                                    lower(replace(
                                        CAST(upload.actor_id AS TEXT),
                                        '-',
                                        '')) ||
                                    ':' ||
                                    lower(replace(
                                        CAST(quota_reservations.id AS TEXT),
                                        '-',
                                        ''))
                                FROM upload_sessions AS upload
                                WHERE upload.tenant_id =
                                    quota_reservations.tenant_id
                                  AND upload.id =
                                    quota_reservations.upload_session_id
                            ))
                    END,
                    request_fingerprint = COALESCE(
                        (
                            SELECT request.request_hash
                            FROM idempotency_requests AS request
                            WHERE request.tenant_id = quota_reservations.tenant_id
                              AND request.upload_session_id = quota_reservations.upload_session_id
                            LIMIT 1
                        ),
                        'legacy:' ||
                        lower(replace(CAST(id AS TEXT), '-', ''))),
                    reserved_uploads = CASE
                        WHEN upload_session_id IS NULL THEN 0
                        ELSE 1
                    END,
                    created_at_utc = COALESCE(
                        (
                            SELECT CASE
                                WHEN julianday(upload.created_at_utc) <
                                     julianday(quota_reservations.expires_at_utc)
                                    THEN upload.created_at_utc
                                ELSE strftime(
                                    '%Y-%m-%dT%H:%M:%fZ',
                                    quota_reservations.expires_at_utc,
                                    '-1 second')
                            END
                            FROM upload_sessions AS upload
                            WHERE upload.tenant_id = quota_reservations.tenant_id
                              AND upload.id = quota_reservations.upload_session_id
                        ),
                        strftime(
                            '%Y-%m-%dT%H:%M:%fZ',
                            expires_at_utc,
                            '-1 second')),
                    updated_at_utc = COALESCE(
                        (
                            SELECT upload.updated_at_utc
                            FROM upload_sessions AS upload
                            WHERE upload.tenant_id = quota_reservations.tenant_id
                              AND upload.id = quota_reservations.upload_session_id
                        ),
                        strftime(
                            '%Y-%m-%dT%H:%M:%fZ',
                            expires_at_utc,
                            '-1 second')),
                    version = CASE
                        WHEN state = 'Reserved' THEN 1
                        ELSE 2
                    END;
                """);

            migrationBuilder.CreateTable(
                name: "audit_events",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    actor_kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    actor_identifier = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    action = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    resource_type = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    resource_identifier = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    before_json = table.Column<string>(type: "text", nullable: false),
                    after_json = table.Column<string>(type: "text", nullable: false),
                    outcome = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    occurred_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_audit_events", x => x.id);
                    table.UniqueConstraint("AK_audit_events_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_audit_events_actor_kind", "\"actor_kind\" IN ('User','ApiKey','System')");
                    table.CheckConstraint("ck_audit_events_outcome", "\"outcome\" IN ('Succeeded','Rejected','Failed')");
                    table.ForeignKey(
                        name: "FK_audit_events_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "event_log",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    sequence = table.Column<long>(type: "INTEGER", nullable: false),
                    event_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    event_type = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    event_version = table.Column<int>(type: "INTEGER", nullable: false),
                    client_payload = table.Column<string>(type: "text", nullable: false),
                    occurred_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    correlation_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    causation_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    retained_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_event_log", x => new { x.tenant_id, x.sequence });
                    table.CheckConstraint("ck_event_log_event_version", "\"event_version\" > 0");
                    table.CheckConstraint("ck_event_log_sequence", "\"sequence\" > 0");
                });

            migrationBuilder.CreateTable(
                name: "ingest_operations",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    operation_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    upload_session_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    fenced_upload_version = table.Column<long>(type: "INTEGER", nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    promotion_mode = table.Column<string>(type: "TEXT", maxLength: 32, nullable: true),
                    canonical_key = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    storage_provider = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    verified_sha256 = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    verified_size_bytes = table.Column<long>(type: "INTEGER", nullable: true),
                    detected_format = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    detected_content_type = table.Column<string>(type: "TEXT", maxLength: 255, nullable: true),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    revision_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    blob_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    blob_reused = table.Column<bool>(type: "INTEGER", nullable: true),
                    rejection_code = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    activated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    cleanup_completed_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ingest_operations", x => new { x.tenant_id, x.operation_id });
                    table.CheckConstraint("ck_ingest_operations_fence", "\"fenced_upload_version\" > 0");
                    table.CheckConstraint("ck_ingest_operations_promotion_mode", "\"promotion_mode\" IS NULL OR \"promotion_mode\" IN ('PromoteCreateOnly','ExistingExactBlob')");
                    table.CheckConstraint("ck_ingest_operations_state", "\"state\" IN ('Fenced','Planned','PromotionOutcomeUnknown','Activated','Rejected','CleanupCompleted')");
                    table.CheckConstraint("ck_ingest_operations_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_ingest_operations_asset_revisions_tenant_id_revision_id",
                        columns: x => new { x.tenant_id, x.revision_id },
                        principalTable: "asset_revisions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ingest_operations_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ingest_operations_blobs_tenant_id_blob_id",
                        columns: x => new { x.tenant_id, x.blob_id },
                        principalTable: "blobs",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ingest_operations_upload_sessions_tenant_id_upload_session_id",
                        columns: x => new { x.tenant_id, x.upload_session_id },
                        principalTable: "upload_sessions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "jobs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    type = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    payload = table.Column<string>(type: "text", nullable: false),
                    payload_version = table.Column<int>(type: "INTEGER", nullable: false),
                    dedupe_key = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    priority = table.Column<int>(type: "INTEGER", nullable: false),
                    max_attempts = table.Column<int>(type: "INTEGER", nullable: false),
                    attempts = table.Column<int>(type: "INTEGER", nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    available_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    trace_parent = table.Column<string>(type: "TEXT", maxLength: 512, nullable: true),
                    lease_owner = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                    lease_acquired_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    lease_heartbeat_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    lease_expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    failure_code = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                    completed_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_jobs", x => x.id);
                    table.CheckConstraint("ck_jobs_attempts", "\"attempts\" >= 0 AND \"attempts\" <= \"max_attempts\"");
                    table.CheckConstraint("ck_jobs_lease", "(\"state\" = 'Leased' AND \"lease_owner\" IS NOT NULL AND \"lease_acquired_at_utc\" IS NOT NULL AND \"lease_heartbeat_at_utc\" IS NOT NULL AND \"lease_expires_at_utc\" IS NOT NULL) OR (\"state\" <> 'Leased' AND \"lease_owner\" IS NULL AND \"lease_acquired_at_utc\" IS NULL AND \"lease_heartbeat_at_utc\" IS NULL AND \"lease_expires_at_utc\" IS NULL)");
                    table.CheckConstraint("ck_jobs_max_attempts", "\"max_attempts\" >= 1");
                    table.CheckConstraint("ck_jobs_payload_version", "\"payload_version\" >= 1");
                    table.CheckConstraint("ck_jobs_state", "\"state\" IN ('Pending','Leased','RetryScheduled','Completed','DeadLettered')");
                    table.CheckConstraint("ck_jobs_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "outbox_messages",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    sequence = table.Column<long>(type: "INTEGER", nullable: false),
                    event_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    event_type = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    event_version = table.Column<int>(type: "INTEGER", nullable: false),
                    client_payload = table.Column<string>(type: "text", nullable: false),
                    occurred_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    correlation_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    causation_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    available_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    claim_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    claimed_by = table.Column<Guid>(type: "TEXT", nullable: true),
                    claimed_until_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    attempts = table.Column<int>(type: "INTEGER", nullable: false),
                    last_error_code = table.Column<string>(type: "TEXT", maxLength: 200, nullable: true),
                    published_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_outbox_messages", x => x.id);
                    table.CheckConstraint("ck_outbox_attempts", "\"attempts\" >= 0");
                    table.CheckConstraint("ck_outbox_event_version", "\"event_version\" > 0");
                    table.CheckConstraint("ck_outbox_sequence", "\"sequence\" > 0");
                    table.CheckConstraint("ck_outbox_version", "\"version\" > 0");
                });

            migrationBuilder.CreateTable(
                name: "outbox_sequences",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    current_sequence = table.Column<long>(type: "INTEGER", nullable: false),
                    last_published_sequence = table.Column<long>(type: "INTEGER", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_outbox_sequences", x => x.tenant_id);
                    table.CheckConstraint("ck_outbox_sequences_current", "\"current_sequence\" > 0");
                    table.CheckConstraint("ck_outbox_sequences_published", "\"last_published_sequence\" >= 0 AND \"last_published_sequence\" <= \"current_sequence\"");
                    table.CheckConstraint("ck_outbox_sequences_version", "\"version\" > 0");
                });

            migrationBuilder.CreateTable(
                name: "quota_usage",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    committed_uploads = table.Column<long>(type: "INTEGER", nullable: false),
                    committed_bytes = table.Column<long>(type: "INTEGER", nullable: false),
                    committed_objects = table.Column<long>(type: "INTEGER", nullable: false),
                    committed_compute_units = table.Column<long>(type: "INTEGER", nullable: false),
                    committed_jobs = table.Column<long>(type: "INTEGER", nullable: false),
                    committed_budget_units = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_uploads = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_bytes = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_objects = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_compute_units = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_jobs = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_budget_units = table.Column<long>(type: "INTEGER", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_quota_usage", x => x.tenant_id);
                    table.CheckConstraint("ck_quota_usage_committed", "\"committed_uploads\" >= 0 AND \"committed_bytes\" >= 0 AND \"committed_objects\" >= 0 AND \"committed_compute_units\" >= 0 AND \"committed_jobs\" >= 0 AND \"committed_budget_units\" >= 0");
                    table.CheckConstraint("ck_quota_usage_reserved", "\"reserved_uploads\" >= 0 AND \"reserved_bytes\" >= 0 AND \"reserved_objects\" >= 0 AND \"reserved_compute_units\" >= 0 AND \"reserved_jobs\" >= 0 AND \"reserved_budget_units\" >= 0");
                    table.CheckConstraint("ck_quota_usage_version", "\"version\" >= 0");
                    table.ForeignKey(
                        name: "FK_quota_usage_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.Sql(
                """
                INSERT INTO quota_usage (
                    tenant_id,
                    committed_uploads,
                    committed_bytes,
                    committed_objects,
                    committed_compute_units,
                    committed_jobs,
                    committed_budget_units,
                    reserved_uploads,
                    reserved_bytes,
                    reserved_objects,
                    reserved_compute_units,
                    reserved_jobs,
                    reserved_budget_units,
                    version)
                SELECT
                    tenant_id,
                    0,
                    SUM(CASE WHEN state = 'Consumed' THEN reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN state = 'Consumed' THEN reserved_objects ELSE 0 END),
                    SUM(CASE WHEN state = 'Consumed' THEN reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN state = 'Consumed' THEN reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN state = 'Consumed' THEN reserved_budget_units ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_uploads ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_objects ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN state = 'Reserved' THEN reserved_budget_units ELSE 0 END),
                    COUNT(*)
                FROM quota_reservations
                GROUP BY tenant_id;
                """);

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_bytes",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_objects",
                table: "quota_reservations");

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_tenant_id_activated_asset_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_tenant_id_activated_blob_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_blob_id" });

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_tenant_id_activated_revision_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_tenant_id_ingest_operation_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "ingest_operation_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_quota_reservations_tenant_id_consumed_by_operation_id",
                table: "quota_reservations",
                columns: new[] { "tenant_id", "consumed_by_operation_id" });

            migrationBuilder.CreateIndex(
                name: "IX_quota_reservations_tenant_id_idempotency_key",
                table: "quota_reservations",
                columns: new[] { "tenant_id", "idempotency_key" },
                unique: true);

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_budget",
                table: "quota_reservations",
                sql: "\"reserved_budget_units\" >= 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_bytes",
                table: "quota_reservations",
                sql: "\"reserved_bytes\" >= 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_jobs",
                table: "quota_reservations",
                sql: "\"reserved_jobs\" >= 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_nonzero",
                table: "quota_reservations",
                sql: "\"reserved_uploads\" > 0 OR \"reserved_bytes\" > 0 OR \"reserved_objects\" > 0 OR \"reserved_compute_units\" > 0 OR \"reserved_jobs\" > 0 OR \"reserved_budget_units\" > 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_objects",
                table: "quota_reservations",
                sql: "\"reserved_objects\" >= 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_uploads",
                table: "quota_reservations",
                sql: "\"reserved_uploads\" >= 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_version",
                table: "quota_reservations",
                sql: "\"version\" >= 1");

            migrationBuilder.CreateIndex(
                name: "IX_audit_events_tenant_id_occurred_at_utc_id",
                table: "audit_events",
                columns: new[] { "tenant_id", "occurred_at_utc", "id" });

            migrationBuilder.CreateIndex(
                name: "IX_audit_events_tenant_id_resource_type_resource_identifier",
                table: "audit_events",
                columns: new[] { "tenant_id", "resource_type", "resource_identifier" });

            migrationBuilder.CreateIndex(
                name: "IX_event_log_event_id",
                table: "event_log",
                column: "event_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_event_log_tenant_id_retained_at_utc_sequence",
                table: "event_log",
                columns: new[] { "tenant_id", "retained_at_utc", "sequence" });

            migrationBuilder.CreateIndex(
                name: "IX_ingest_operations_tenant_id_asset_id",
                table: "ingest_operations",
                columns: new[] { "tenant_id", "asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_ingest_operations_tenant_id_blob_id",
                table: "ingest_operations",
                columns: new[] { "tenant_id", "blob_id" });

            migrationBuilder.CreateIndex(
                name: "IX_ingest_operations_tenant_id_revision_id",
                table: "ingest_operations",
                columns: new[] { "tenant_id", "revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_ingest_operations_tenant_id_upload_session_id",
                table: "ingest_operations",
                columns: new[] { "tenant_id", "upload_session_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_jobs_lease_expires_at_utc",
                table: "jobs",
                column: "lease_expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_jobs_state_available_at_utc_priority_created_at_utc",
                table: "jobs",
                columns: new[] { "state", "available_at_utc", "priority", "created_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_jobs_tenant_id_dedupe_key",
                table: "jobs",
                columns: new[] { "tenant_id", "dedupe_key" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_outbox_messages_event_id",
                table: "outbox_messages",
                column: "event_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_outbox_messages_tenant_id_published_at_utc_available_at_utc_sequence",
                table: "outbox_messages",
                columns: new[] { "tenant_id", "published_at_utc", "available_at_utc", "sequence" });

            migrationBuilder.CreateIndex(
                name: "IX_outbox_messages_tenant_id_sequence",
                table: "outbox_messages",
                columns: new[] { "tenant_id", "sequence" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_quota_reservations_ingest_operations_tenant_id_consumed_by_operation_id",
                table: "quota_reservations",
                columns: new[] { "tenant_id", "consumed_by_operation_id" },
                principalTable: "ingest_operations",
                principalColumns: new[] { "tenant_id", "operation_id" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_upload_sessions_asset_revisions_tenant_id_activated_revision_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_revision_id" },
                principalTable: "asset_revisions",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_upload_sessions_assets_tenant_id_activated_asset_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_upload_sessions_blobs_tenant_id_activated_blob_id",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "activated_blob_id" },
                principalTable: "blobs",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_quota_reservations_ingest_operations_tenant_id_consumed_by_operation_id",
                table: "quota_reservations");

            migrationBuilder.DropForeignKey(
                name: "FK_upload_sessions_asset_revisions_tenant_id_activated_revision_id",
                table: "upload_sessions");

            migrationBuilder.DropForeignKey(
                name: "FK_upload_sessions_assets_tenant_id_activated_asset_id",
                table: "upload_sessions");

            migrationBuilder.DropForeignKey(
                name: "FK_upload_sessions_blobs_tenant_id_activated_blob_id",
                table: "upload_sessions");

            migrationBuilder.DropTable(
                name: "audit_events");

            migrationBuilder.DropTable(
                name: "event_log");

            migrationBuilder.DropTable(
                name: "ingest_operations");

            migrationBuilder.DropTable(
                name: "jobs");

            migrationBuilder.DropTable(
                name: "outbox_messages");

            migrationBuilder.DropTable(
                name: "outbox_sequences");

            migrationBuilder.DropTable(
                name: "quota_usage");

            migrationBuilder.DropIndex(
                name: "IX_upload_sessions_tenant_id_activated_asset_id",
                table: "upload_sessions");

            migrationBuilder.DropIndex(
                name: "IX_upload_sessions_tenant_id_activated_blob_id",
                table: "upload_sessions");

            migrationBuilder.DropIndex(
                name: "IX_upload_sessions_tenant_id_activated_revision_id",
                table: "upload_sessions");

            migrationBuilder.DropIndex(
                name: "IX_upload_sessions_tenant_id_ingest_operation_id",
                table: "upload_sessions");

            migrationBuilder.DropIndex(
                name: "IX_quota_reservations_tenant_id_consumed_by_operation_id",
                table: "quota_reservations");

            migrationBuilder.DropIndex(
                name: "IX_quota_reservations_tenant_id_idempotency_key",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_budget",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_bytes",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_jobs",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_nonzero",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_objects",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_uploads",
                table: "quota_reservations");

            migrationBuilder.DropCheckConstraint(
                name: "ck_quota_reservations_version",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "activated_asset_id",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "activated_blob_id",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "activated_revision_id",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "cleanup_completed_at_utc",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "commit_idempotency_key",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "commit_request_hash",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "display_file_name",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "ingest_operation_id",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_expires_at_utc",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_max_part_bytes",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_max_parts",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_min_part_bytes",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "rejected_at_utc",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "rejection_code",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "staging_entity_tag",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "staging_provider_checksum",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "staging_provider_version",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "storage_container",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "storage_provider",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "consumed_by_operation_id",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "created_at_utc",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "idempotency_key",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "request_fingerprint",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "reserved_budget_units",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "reserved_jobs",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "reserved_uploads",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "updated_at_utc",
                table: "quota_reservations");

            migrationBuilder.DropColumn(
                name: "version",
                table: "quota_reservations");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_bytes",
                table: "quota_reservations",
                sql: "\"reserved_bytes\" > 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_quota_reservations_objects",
                table: "quota_reservations",
                sql: "\"reserved_objects\" > 0");
        }
    }
}
