// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Sqlite.Migrations
{
    /// <inheritdoc />
    public partial class NormalizeLegacyRuntimeData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                UPDATE quota_reservations
                SET expires_at_utc = '0001-01-01T00:00:01.000Z'
                WHERE julianday(expires_at_utc) <=
                    julianday('0001-01-01T00:00:00.000Z');

                UPDATE quota_reservations
                SET
                    idempotency_key = CASE
                        WHEN upload_session_id IS NULL THEN CASE
                            WHEN idempotency_key = '' OR
                                 lower(replace(idempotency_key, '-', '')) =
                                 lower(replace(CAST(id AS TEXT), '-', ''))
                                THEN
                                    'legacy-reservation:' ||
                                    lower(replace(
                                        CAST(id AS TEXT),
                                        '-',
                                        ''))
                            ELSE idempotency_key
                        END
                        ELSE COALESCE(
                            (
                                SELECT CASE
                                    WHEN length(request.key) <= 160 THEN
                                        'upload:' ||
                                        lower(replace(
                                            CAST(upload.actor_id AS TEXT),
                                            '-',
                                            '')) ||
                                        ':' ||
                                        request.key
                                    ELSE
                                        'legacy-upload:' ||
                                        lower(replace(
                                            CAST(upload.actor_id AS TEXT),
                                            '-',
                                            '')) ||
                                        ':' ||
                                        lower(replace(
                                            CAST(quota_reservations.id AS TEXT),
                                            '-',
                                            ''))
                                END
                                FROM upload_sessions AS upload
                                JOIN idempotency_requests AS request
                                  ON request.tenant_id = upload.tenant_id
                                 AND request.upload_session_id = upload.id
                                WHERE upload.tenant_id =
                                    quota_reservations.tenant_id
                                  AND upload.id =
                                    quota_reservations.upload_session_id
                                LIMIT 1
                            ),
                            (
                                SELECT
                                    'legacy-upload:' ||
                                    lower(replace(
                                        CAST(upload.actor_id AS TEXT),
                                        '-',
                                        '')) ||
                                    ':' ||
                                    lower(replace(
                                        CAST(quota_reservations.id AS TEXT),
                                        '-',
                                        ''))
                                FROM upload_sessions AS upload
                                WHERE upload.tenant_id =
                                    quota_reservations.tenant_id
                                  AND upload.id =
                                    quota_reservations.upload_session_id
                            ))
                    END,
                    request_fingerprint = CASE
                        WHEN request_fingerprint = '' THEN COALESCE(
                            (
                                SELECT request.request_hash
                                FROM idempotency_requests AS request
                                WHERE request.tenant_id =
                                    quota_reservations.tenant_id
                                  AND request.upload_session_id =
                                    quota_reservations.upload_session_id
                                LIMIT 1
                            ),
                            'legacy:' ||
                            lower(replace(CAST(id AS TEXT), '-', '')))
                        ELSE request_fingerprint
                    END,
                    created_at_utc = CASE
                        WHEN julianday(created_at_utc) <
                             julianday(expires_at_utc)
                            THEN created_at_utc
                        ELSE strftime(
                            '%Y-%m-%dT%H:%M:%fZ',
                            expires_at_utc,
                            '-1 second')
                    END,
                    updated_at_utc = CASE
                        WHEN julianday(updated_at_utc) <
                             julianday(created_at_utc)
                            THEN created_at_utc
                        ELSE updated_at_utc
                    END,
                    version = CASE WHEN version < 1 THEN 1 ELSE version END;

                UPDATE quota_reservations
                SET
                    state = 'Expired',
                    updated_at_utc = CASE
                        WHEN updated_at_utc < expires_at_utc
                            THEN expires_at_utc
                        ELSE updated_at_utc
                    END,
                    version = version + 1
                WHERE state = 'Reserved'
                  AND EXISTS (
                      SELECT 1
                      FROM upload_sessions AS upload
                      WHERE upload.tenant_id = quota_reservations.tenant_id
                        AND upload.id = quota_reservations.upload_session_id
                        AND upload.strategy = 'Multipart'
                        AND upload.provider_upload_id IS NOT NULL
                        AND upload.state IN (
                            'Pending',
                            'UploadIssued',
                            'Committing',
                            'Aborting',
                            'OutcomeUnknown',
                            'Reconciling')
                        AND (
                            upload.multipart_provider_state IS NULL OR
                            upload.multipart_expires_at_utc IS NULL OR
                            upload.multipart_part_plan_lifetime_ticks IS NULL OR
                            upload.multipart_max_parts IS NULL OR
                            upload.multipart_min_part_bytes IS NULL OR
                            upload.multipart_max_part_bytes IS NULL)
                        AND COALESCE(upload.storage_provider, '') NOT IN (
                            'azure',
                            'aws-s3',
                            'cloudflare-r2',
                            'backblaze-b2',
                            'minio')
                  );

                UPDATE upload_sessions AS upload
                SET
                    multipart_provider_state = CASE
                        WHEN storage_provider = 'azure' THEN
                            'azure-block:v1:' || provider_upload_id
                        WHEN storage_provider IN (
                            'aws-s3',
                            'cloudflare-r2',
                            'backblaze-b2',
                            'minio') THEN
                            's3:v1:' || provider_upload_id
                        ELSE
                            'legacy-unrecoverable:v1:' || provider_upload_id
                    END,
                    provider_upload_id = CASE
                        WHEN storage_provider = 'azure' OR
                             storage_provider IN (
                                 'aws-s3',
                                 'cloudflare-r2',
                                 'backblaze-b2',
                                 'minio')
                            THEN provider_upload_id
                        ELSE NULL
                    END,
                    multipart_expires_at_utc = CASE
                        WHEN storage_provider = 'azure' OR
                             storage_provider IN (
                                 'aws-s3',
                                 'cloudflare-r2',
                                 'backblaze-b2',
                                 'minio')
                            THEN COALESCE(
                                multipart_expires_at_utc,
                                expires_at_utc)
                        ELSE NULL
                    END,
                    multipart_part_plan_lifetime_ticks = CASE
                        WHEN storage_provider = 'azure' OR
                             storage_provider IN (
                                 'aws-s3',
                                 'cloudflare-r2',
                                 'backblaze-b2',
                                 'minio')
                            THEN 1
                        ELSE NULL
                    END,
                    multipart_max_parts = CASE
                        WHEN storage_provider = 'azure' THEN 50000
                        WHEN storage_provider IN (
                            'aws-s3',
                            'cloudflare-r2',
                            'backblaze-b2',
                            'minio') THEN 10000
                        ELSE NULL
                    END,
                    multipart_min_part_bytes = CASE
                        WHEN storage_provider = 'azure' THEN 1
                        WHEN storage_provider IN (
                            'aws-s3',
                            'cloudflare-r2',
                            'backblaze-b2',
                            'minio') THEN 5242880
                        ELSE NULL
                    END,
                    multipart_max_part_bytes = CASE
                        WHEN storage_provider = 'azure' THEN 4000000000
                        WHEN storage_provider IN (
                            'aws-s3',
                            'cloudflare-r2',
                            'backblaze-b2',
                            'minio') THEN 5368709120
                        ELSE NULL
                    END,
                    last_known_state = CASE
                        WHEN storage_provider = 'azure' OR
                             storage_provider IN (
                                 'aws-s3',
                                 'cloudflare-r2',
                                 'backblaze-b2',
                                 'minio')
                            THEN 'Aborting'
                        ELSE COALESCE(last_known_state, state)
                    END,
                    state = CASE
                        WHEN storage_provider = 'azure' OR
                             storage_provider IN (
                                 'aws-s3',
                                 'cloudflare-r2',
                                 'backblaze-b2',
                                 'minio')
                            THEN 'OutcomeUnknown'
                        ELSE 'Expired'
                    END,
                    updated_at_utc = CASE
                        WHEN COALESCE(storage_provider, '') NOT IN (
                                    'azure',
                                    'aws-s3',
                                    'cloudflare-r2',
                                    'backblaze-b2',
                                    'minio') AND
                             updated_at_utc < expires_at_utc
                            THEN expires_at_utc
                        ELSE updated_at_utc
                    END,
                    version = version + 1
                WHERE strategy = 'Multipart'
                  AND provider_upload_id IS NOT NULL
                  AND state IN (
                      'Pending',
                      'UploadIssued',
                      'Committing',
                      'Aborting',
                      'OutcomeUnknown',
                      'Reconciling')
                  AND (
                      multipart_provider_state IS NULL OR
                      multipart_expires_at_utc IS NULL OR
                      multipart_part_plan_lifetime_ticks IS NULL OR
                      multipart_max_parts IS NULL OR
                      multipart_min_part_bytes IS NULL OR
                      multipart_max_part_bytes IS NULL);

                UPDATE quota_usage
                SET
                    committed_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    reserved_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0);

                INSERT INTO authentication_routes (
                    lookup_digest,
                    kind,
                    routed_tenant_id,
                    principal_id,
                    credential_id,
                    created_at_utc)
                SELECT
                    lower(replace(CAST(key_row.id AS TEXT), '-', '')) ||
                    lower(replace(CAST(key_row.id AS TEXT), '-', '')),
                    'ApiKey',
                    key_row.tenant_id,
                    key_row.owner_id,
                    key_row.id,
                    key_row.created_at_utc
                FROM api_keys AS key_row
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM authentication_routes AS route
                    WHERE route.kind = 'ApiKey'
                      AND route.credential_id = key_row.id
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Normalized legacy rows remain valid under the preceding schema.
        }
    }
}
