// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Sqlite.Migrations
{
    /// <inheritdoc />
    public partial class AddWorkerTenantCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "worker_tenant_catalog",
                columns: table => new
                {
                    routed_tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    worker_enabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_worker_tenant_catalog", x => x.routed_tenant_id);
                    table.CheckConstraint("ck_worker_tenant_catalog_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_worker_tenant_catalog_tenants_routed_tenant_id",
                        column: x => x.routed_tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.Sql(
                """
                INSERT INTO worker_tenant_catalog (
                    routed_tenant_id,
                    worker_enabled,
                    updated_at_utc,
                    version)
                SELECT
                    tenant.id,
                    CASE WHEN tenant.status = 'Active' THEN 1 ELSE 0 END,
                    tenant.updated_at_utc,
                    tenant.version
                FROM tenants AS tenant;
                """);

            migrationBuilder.CreateIndex(
                name: "IX_worker_tenant_catalog_worker_enabled_routed_tenant_id",
                table: "worker_tenant_catalog",
                columns: new[] { "worker_enabled", "routed_tenant_id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "worker_tenant_catalog");
        }
    }
}
