// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Sqlite.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "revoked_tokens",
                columns: table => new
                {
                    issuer = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false),
                    jti = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    reason = table.Column<string>(type: "TEXT", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_revoked_tokens", x => new { x.issuer, x.jti });
                });

            migrationBuilder.CreateTable(
                name: "tenants",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    slug = table.Column<string>(type: "TEXT", maxLength: 63, nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    settings_json = table.Column<string>(type: "text", nullable: false),
                    quotas_json = table.Column<string>(type: "text", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tenants", x => x.id);
                    table.UniqueConstraint("AK_tenants_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_tenants_identity", "\"id\" = \"tenant_id\"");
                    table.CheckConstraint("ck_tenants_status", "\"status\" IN ('Active','Suspended','Deactivated')");
                    table.CheckConstraint("ck_tenants_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "users",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    normalized_email = table.Column<string>(type: "TEXT", maxLength: 320, nullable: false),
                    display_name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_users", x => x.id);
                    table.CheckConstraint("ck_users_status", "\"status\" IN ('Active','Suspended','Disabled')");
                    table.CheckConstraint("ck_users_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "blobs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    provider = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    container = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    object_key = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: false),
                    provider_version = table.Column<string>(type: "TEXT", maxLength: 512, nullable: true),
                    sha256 = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    provider_checksum = table.Column<string>(type: "TEXT", maxLength: 512, nullable: true),
                    size_bytes = table.Column<long>(type: "INTEGER", nullable: false),
                    content_type = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_blobs", x => x.id);
                    table.UniqueConstraint("AK_blobs_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_blobs_sha256", "length(\"sha256\") = 64");
                    table.CheckConstraint("ck_blobs_size", "\"size_bytes\" > 0");
                    table.CheckConstraint("ck_blobs_state", "\"state\" IN ('Staging','Quarantined','Active','Deleting','Deleted','Missing')");
                    table.ForeignKey(
                        name: "FK_blobs_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "deletion_tombstones",
                columns: table => new
                {
                    former_asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    purged_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    backup_expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    relationship_count = table.Column<int>(type: "INTEGER", nullable: false),
                    relationship_digest = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_deletion_tombstones", x => new { x.tenant_id, x.former_asset_id });
                    table.CheckConstraint("ck_deletion_tombstones_backup", "\"backup_expires_at_utc\" >= \"purged_at_utc\"");
                    table.CheckConstraint("ck_deletion_tombstones_relationships", "\"relationship_count\" >= 0 AND length(\"relationship_digest\") = 64");
                    table.ForeignKey(
                        name: "FK_deletion_tombstones_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "purge_batches",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    requested_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    requested_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    approved_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    approved_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    dry_run_hash = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                    dry_run_completed_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    candidate_count = table.Column<int>(type: "INTEGER", nullable: false),
                    eligible_count = table.Column<int>(type: "INTEGER", nullable: false),
                    started_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    completed_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_purge_batches", x => x.id);
                    table.UniqueConstraint("AK_purge_batches_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_purge_batches_counts", "\"candidate_count\" >= 0 AND \"eligible_count\" >= 0 AND \"eligible_count\" <= \"candidate_count\"");
                    table.CheckConstraint("ck_purge_batches_state", "\"state\" IN ('Draft','DryRunCompleted','Approved','Executing','Completed','Cancelled')");
                    table.CheckConstraint("ck_purge_batches_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_purge_batches_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "resource_grants",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    resource_kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    resource_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    grantee_kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    grantee_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    role = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    created_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    revoked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    revoked_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_resource_grants", x => x.id);
                    table.UniqueConstraint("AK_resource_grants_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_resource_grants_grantee_kind", "\"grantee_kind\" IN ('User','Group')");
                    table.CheckConstraint("ck_resource_grants_resource_kind", "\"resource_kind\" IN ('Album','Asset')");
                    table.CheckConstraint("ck_resource_grants_role", "\"role\" IN ('Viewer','Contributor','Curator')");
                    table.CheckConstraint("ck_resource_grants_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_resource_grants_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "tags",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    normalized_name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    display_name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    color = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tags", x => x.id);
                    table.UniqueConstraint("AK_tags_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_tags_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_tags_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "api_keys",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    owner_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    prefix = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    digest = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    scopes = table.Column<int>(type: "INTEGER", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    revoked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    last_used_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_api_keys", x => x.id);
                    table.UniqueConstraint("AK_api_keys_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_api_keys_scopes", "\"scopes\" > 0 AND \"scopes\" <= 15");
                    table.CheckConstraint("ck_api_keys_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_api_keys_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_api_keys_users_owner_id",
                        column: x => x.owner_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "auth_sessions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    digest = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    revoked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_auth_sessions", x => x.id);
                    table.CheckConstraint("ck_auth_sessions_expiry", "\"expires_at_utc\" > \"created_at_utc\"");
                    table.CheckConstraint("ck_auth_sessions_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_auth_sessions_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "external_identities",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    issuer = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false),
                    subject = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    linked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_external_identities", x => x.id);
                    table.ForeignKey(
                        name: "FK_external_identities_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "local_identities",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    normalized_login = table.Column<string>(type: "TEXT", maxLength: 320, nullable: false),
                    linked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_local_identities", x => x.id);
                    table.ForeignKey(
                        name: "FK_local_identities_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tenant_memberships",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    role = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    status = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    invited_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    joined_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tenant_memberships", x => new { x.tenant_id, x.user_id });
                    table.CheckConstraint("ck_tenant_memberships_role", "\"role\" IN ('TenantOwner','TenantAdmin','Member','Viewer')");
                    table.CheckConstraint("ck_tenant_memberships_status", "\"status\" IN ('Invited','Active','Suspended','Removed')");
                    table.CheckConstraint("ck_tenant_memberships_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_tenant_memberships_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_tenant_memberships_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "upload_sessions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    actor_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    strategy = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    staging_key = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: false),
                    provider_upload_id = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    expected_bytes = table.Column<long>(type: "INTEGER", nullable: false),
                    expected_sha256 = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    declared_content_type = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    last_known_state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: true),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_upload_sessions", x => x.id);
                    table.UniqueConstraint("AK_upload_sessions_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_upload_sessions_expected_bytes", "\"expected_bytes\" > 0");
                    table.CheckConstraint("ck_upload_sessions_state", "\"state\" IN ('Pending','UploadIssued','CommitRequested','Verifying','Promoting','Accepted','Aborted','Expired','Rejected','OutcomeUnknown','Reconciling')");
                    table.CheckConstraint("ck_upload_sessions_strategy", "\"strategy\" IN ('Proxy','Direct','Multipart')");
                    table.CheckConstraint("ck_upload_sessions_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_upload_sessions_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_upload_sessions_users_actor_id",
                        column: x => x.actor_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "purge_batch_items",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    purge_batch_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    revision = table.Column<long>(type: "INTEGER", nullable: false),
                    result = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    reclaimed_bytes = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_purge_batch_items", x => new { x.tenant_id, x.purge_batch_id, x.asset_id });
                    table.CheckConstraint("ck_purge_batch_items_bytes", "\"reclaimed_bytes\" >= 0");
                    table.CheckConstraint("ck_purge_batch_items_result", "\"result\" IN ('Purged','Blocked','Failed')");
                    table.CheckConstraint("ck_purge_batch_items_revision", "\"revision\" > 0");
                    table.ForeignKey(
                        name: "FK_purge_batch_items_purge_batches_tenant_id_purge_batch_id",
                        columns: x => new { x.tenant_id, x.purge_batch_id },
                        principalTable: "purge_batches",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "idempotency_requests",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    principal_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    key = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    request_hash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    upload_session_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    response_reference = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_idempotency_requests", x => new { x.tenant_id, x.principal_id, x.key });
                    table.ForeignKey(
                        name: "FK_idempotency_requests_upload_sessions_tenant_id_upload_session_id",
                        columns: x => new { x.tenant_id, x.upload_session_id },
                        principalTable: "upload_sessions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "quota_reservations",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    upload_session_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    job_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    reserved_bytes = table.Column<long>(type: "INTEGER", nullable: false),
                    reserved_objects = table.Column<int>(type: "INTEGER", nullable: false),
                    reserved_compute_units = table.Column<long>(type: "INTEGER", nullable: false),
                    state = table.Column<string>(type: "TEXT", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_quota_reservations", x => x.id);
                    table.UniqueConstraint("AK_quota_reservations_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_quota_reservations_bytes", "\"reserved_bytes\" > 0");
                    table.CheckConstraint("ck_quota_reservations_compute", "\"reserved_compute_units\" >= 0");
                    table.CheckConstraint("ck_quota_reservations_objects", "\"reserved_objects\" > 0");
                    table.CheckConstraint("ck_quota_reservations_state", "\"state\" IN ('Reserved','Consumed','Released','Expired')");
                    table.ForeignKey(
                        name: "FK_quota_reservations_upload_sessions_tenant_id_upload_session_id",
                        columns: x => new { x.tenant_id, x.upload_session_id },
                        principalTable: "upload_sessions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "upload_parts",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    upload_session_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    part_number = table.Column<int>(type: "INTEGER", nullable: false),
                    entity_tag = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: false),
                    checksum = table.Column<string>(type: "TEXT", maxLength: 512, nullable: true),
                    size_bytes = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_upload_parts", x => new { x.tenant_id, x.upload_session_id, x.part_number });
                    table.CheckConstraint("ck_upload_parts_number", "\"part_number\" > 0");
                    table.CheckConstraint("ck_upload_parts_size", "\"size_bytes\" > 0");
                    table.ForeignKey(
                        name: "FK_upload_parts_upload_sessions_tenant_id_upload_session_id",
                        columns: x => new { x.tenant_id, x.upload_session_id },
                        principalTable: "upload_sessions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "album_items",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    album_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    position = table.Column<long>(type: "INTEGER", nullable: false),
                    added_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    added_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_album_items", x => new { x.tenant_id, x.album_id, x.asset_id });
                    table.CheckConstraint("ck_album_items_position", "\"position\" >= 0");
                    table.ForeignKey(
                        name: "FK_album_items_users_added_by_user_id",
                        column: x => x.added_by_user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "albums",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    owner_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    cover_asset_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    sort_mode = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_albums", x => x.id);
                    table.UniqueConstraint("AK_albums_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_albums_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_albums_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_albums_users_owner_id",
                        column: x => x.owner_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "shares",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    created_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    token_hash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    target_kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    album_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    snapshot_json = table.Column<string>(type: "TEXT", nullable: true),
                    password_hash = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    permissions = table.Column<int>(type: "INTEGER", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    revoked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    revoked_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_shares", x => x.id);
                    table.UniqueConstraint("AK_shares_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_shares_permissions", "(\"permissions\" & 1) = 1 AND \"permissions\" >= 1 AND \"permissions\" <= 7");
                    table.CheckConstraint("ck_shares_target_kind", "\"target_kind\" IN ('Album','Snapshot')");
                    table.CheckConstraint("ck_shares_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_shares_albums_tenant_id_album_id",
                        columns: x => new { x.tenant_id, x.album_id },
                        principalTable: "albums",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "share_sessions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    share_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    digest = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    revoked_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_share_sessions", x => x.id);
                    table.ForeignKey(
                        name: "FK_share_sessions_shares_tenant_id_share_id",
                        columns: x => new { x.tenant_id, x.share_id },
                        principalTable: "shares",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "asset_favorites",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    added_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_asset_favorites", x => new { x.tenant_id, x.user_id, x.asset_id });
                    table.ForeignKey(
                        name: "FK_asset_favorites_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "asset_lifecycles",
                columns: table => new
                {
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    current_revision = table.Column<long>(type: "INTEGER", nullable: false),
                    state = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    has_been_trashed = table.Column<bool>(type: "INTEGER", nullable: false),
                    active_purge_batch_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    purge_requested_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    purge_initiator_kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: true),
                    purge_evaluated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    purge_observed_revision = table.Column<long>(type: "INTEGER", nullable: true),
                    purge_has_blocking_references = table.Column<bool>(type: "INTEGER", nullable: true),
                    last_restored_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    last_restored_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_asset_lifecycles", x => new { x.tenant_id, x.asset_id });
                    table.CheckConstraint("ck_asset_lifecycles_revision", "\"current_revision\" > 0");
                    table.CheckConstraint("ck_asset_lifecycles_state", "\"state\" IN ('Ready','Trashed','Purging','Purged')");
                    table.CheckConstraint("ck_asset_lifecycles_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "relationship_snapshots",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    kind = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    resource_id = table.Column<Guid>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_relationship_snapshots", x => new { x.tenant_id, x.asset_id, x.kind, x.resource_id });
                    table.CheckConstraint("ck_relationship_snapshots_kind", "\"kind\" IN ('Album','Tag','Favorite','Share','Grant')");
                    table.ForeignKey(
                        name: "FK_relationship_snapshots_asset_lifecycles_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "asset_lifecycles",
                        principalColumns: new[] { "tenant_id", "asset_id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "trash_entries",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    deleted_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    deleted_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    purge_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    reason = table.Column<string>(type: "TEXT", maxLength: 2000, nullable: false),
                    restoration_metadata_json = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_trash_entries", x => new { x.tenant_id, x.asset_id });
                    table.CheckConstraint("ck_trash_entries_purge_at", "\"purge_at_utc\" > \"deleted_at_utc\"");
                    table.ForeignKey(
                        name: "FK_trash_entries_asset_lifecycles_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "asset_lifecycles",
                        principalColumns: new[] { "tenant_id", "asset_id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "asset_metadata_history",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    actor_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    source = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    changes_json = table.Column<string>(type: "TEXT", nullable: false),
                    changed_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_asset_metadata_history", x => x.id);
                    table.ForeignKey(
                        name: "FK_asset_metadata_history_users_actor_user_id",
                        column: x => x.actor_user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "asset_revisions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    revision_number = table.Column<long>(type: "INTEGER", nullable: false),
                    blob_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    detected_format = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    detected_content_type = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    width = table.Column<int>(type: "INTEGER", nullable: false),
                    height = table.Column<int>(type: "INTEGER", nullable: false),
                    frame_count = table.Column<int>(type: "INTEGER", nullable: false),
                    safe_metadata_json = table.Column<string>(type: "TEXT", nullable: false),
                    private_metadata_json = table.Column<string>(type: "TEXT", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_asset_revisions", x => x.id);
                    table.UniqueConstraint("AK_asset_revisions_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_asset_revisions_dimensions", "\"width\" > 0 AND \"height\" > 0");
                    table.CheckConstraint("ck_asset_revisions_frames", "\"frame_count\" > 0");
                    table.CheckConstraint("ck_asset_revisions_number", "\"revision_number\" > 0");
                    table.ForeignKey(
                        name: "FK_asset_revisions_blobs_tenant_id_blob_id",
                        columns: x => new { x.tenant_id, x.blob_id },
                        principalTable: "blobs",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "assets",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    owner_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    current_revision_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    title = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    status = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    visibility = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    captured_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    captured_local = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    captured_offset_minutes = table.Column<int>(type: "INTEGER", nullable: true),
                    capture_precision = table.Column<string>(type: "TEXT", maxLength: 32, nullable: true),
                    capture_source = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_assets", x => x.id);
                    table.UniqueConstraint("AK_assets_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_assets_status", "\"status\" IN ('Processing','Ready','Failed','Trashed','Purged')");
                    table.CheckConstraint("ck_assets_version", "\"version\" >= 1");
                    table.CheckConstraint("ck_assets_visibility", "\"visibility\" IN ('Private','Tenant','Public')");
                    table.ForeignKey(
                        name: "FK_assets_asset_revisions_tenant_id_current_revision_id",
                        columns: x => new { x.tenant_id, x.current_revision_id },
                        principalTable: "asset_revisions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_assets_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_assets_users_owner_id",
                        column: x => x.owner_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "asset_tags",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tag_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    source = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_asset_tags", x => new { x.tenant_id, x.asset_id, x.tag_id });
                    table.CheckConstraint("ck_asset_tags_source", "\"source\" IN ('user','import','ai-accepted')");
                    table.ForeignKey(
                        name: "FK_asset_tags_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_asset_tags_tags_tenant_id_tag_id",
                        columns: x => new { x.tenant_id, x.tag_id },
                        principalTable: "tags",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "retention_holds",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "TEXT", nullable: false),
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    reason = table.Column<string>(type: "TEXT", maxLength: 2000, nullable: false),
                    created_by_user_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    released_by_user_id = table.Column<Guid>(type: "TEXT", nullable: true),
                    released_at_utc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_retention_holds", x => x.id);
                    table.CheckConstraint("ck_retention_holds_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_retention_holds_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "share_assets",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    share_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    asset_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    revision_id = table.Column<Guid>(type: "TEXT", nullable: false),
                    revision_number = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_share_assets", x => new { x.tenant_id, x.share_id, x.asset_id });
                    table.CheckConstraint("ck_share_assets_revision", "\"revision_number\" > 0");
                    table.ForeignKey(
                        name: "FK_share_assets_asset_revisions_tenant_id_revision_id",
                        columns: x => new { x.tenant_id, x.revision_id },
                        principalTable: "asset_revisions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_share_assets_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_share_assets_shares_tenant_id_share_id",
                        columns: x => new { x.tenant_id, x.share_id },
                        principalTable: "shares",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_album_items_added_by_user_id",
                table: "album_items",
                column: "added_by_user_id");

            migrationBuilder.CreateIndex(
                name: "IX_album_items_tenant_id_album_id_position",
                table: "album_items",
                columns: new[] { "tenant_id", "album_id", "position" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_album_items_tenant_id_asset_id",
                table: "album_items",
                columns: new[] { "tenant_id", "asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_albums_owner_id",
                table: "albums",
                column: "owner_id");

            migrationBuilder.CreateIndex(
                name: "IX_albums_tenant_id_cover_asset_id",
                table: "albums",
                columns: new[] { "tenant_id", "cover_asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_albums_tenant_id_owner_id",
                table: "albums",
                columns: new[] { "tenant_id", "owner_id" });

            migrationBuilder.CreateIndex(
                name: "IX_api_keys_owner_id",
                table: "api_keys",
                column: "owner_id");

            migrationBuilder.CreateIndex(
                name: "IX_api_keys_prefix",
                table: "api_keys",
                column: "prefix",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_api_keys_tenant_id_owner_id",
                table: "api_keys",
                columns: new[] { "tenant_id", "owner_id" });

            migrationBuilder.CreateIndex(
                name: "IX_asset_favorites_tenant_id_asset_id",
                table: "asset_favorites",
                columns: new[] { "tenant_id", "asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_asset_favorites_user_id",
                table: "asset_favorites",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_asset_metadata_history_actor_user_id",
                table: "asset_metadata_history",
                column: "actor_user_id");

            migrationBuilder.CreateIndex(
                name: "IX_asset_metadata_history_tenant_id_asset_id_changed_at_utc",
                table: "asset_metadata_history",
                columns: new[] { "tenant_id", "asset_id", "changed_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_asset_revisions_tenant_id_asset_id_revision_number",
                table: "asset_revisions",
                columns: new[] { "tenant_id", "asset_id", "revision_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_asset_revisions_tenant_id_blob_id",
                table: "asset_revisions",
                columns: new[] { "tenant_id", "blob_id" });

            migrationBuilder.CreateIndex(
                name: "IX_asset_tags_tenant_id_tag_id",
                table: "asset_tags",
                columns: new[] { "tenant_id", "tag_id" });

            migrationBuilder.CreateIndex(
                name: "IX_assets_owner_id",
                table: "assets",
                column: "owner_id");

            migrationBuilder.CreateIndex(
                name: "IX_assets_tenant_id_created_at_utc_id",
                table: "assets",
                columns: new[] { "tenant_id", "created_at_utc", "id" });

            migrationBuilder.CreateIndex(
                name: "IX_assets_tenant_id_current_revision_id",
                table: "assets",
                columns: new[] { "tenant_id", "current_revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_assets_tenant_id_owner_id",
                table: "assets",
                columns: new[] { "tenant_id", "owner_id" });

            migrationBuilder.CreateIndex(
                name: "IX_auth_sessions_digest",
                table: "auth_sessions",
                column: "digest",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_auth_sessions_user_id",
                table: "auth_sessions",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_blobs_tenant_id_provider_container_object_key_provider_version",
                table: "blobs",
                columns: new[] { "tenant_id", "provider", "container", "object_key", "provider_version" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_blobs_tenant_id_sha256_size_bytes",
                table: "blobs",
                columns: new[] { "tenant_id", "sha256", "size_bytes" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_deletion_tombstones_backup_expires_at_utc",
                table: "deletion_tombstones",
                column: "backup_expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_external_identities_issuer_subject",
                table: "external_identities",
                columns: new[] { "issuer", "subject" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_external_identities_user_id",
                table: "external_identities",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_idempotency_requests_expires_at_utc",
                table: "idempotency_requests",
                column: "expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_idempotency_requests_tenant_id_upload_session_id",
                table: "idempotency_requests",
                columns: new[] { "tenant_id", "upload_session_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_local_identities_normalized_login",
                table: "local_identities",
                column: "normalized_login",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_local_identities_user_id",
                table: "local_identities",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_purge_batches_tenant_id_state_requested_at_utc",
                table: "purge_batches",
                columns: new[] { "tenant_id", "state", "requested_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_quota_reservations_expires_at_utc",
                table: "quota_reservations",
                column: "expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_quota_reservations_tenant_id_upload_session_id",
                table: "quota_reservations",
                columns: new[] { "tenant_id", "upload_session_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_resource_grants_tenant_id_resource_kind_resource_id_grantee_kind_grantee_id",
                table: "resource_grants",
                columns: new[] { "tenant_id", "resource_kind", "resource_id", "grantee_kind", "grantee_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_retention_holds_tenant_id_asset_id_released_at_utc",
                table: "retention_holds",
                columns: new[] { "tenant_id", "asset_id", "released_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_revoked_tokens_expires_at_utc",
                table: "revoked_tokens",
                column: "expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_share_assets_tenant_id_asset_id",
                table: "share_assets",
                columns: new[] { "tenant_id", "asset_id" });

            migrationBuilder.CreateIndex(
                name: "IX_share_assets_tenant_id_revision_id",
                table: "share_assets",
                columns: new[] { "tenant_id", "revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_share_sessions_digest",
                table: "share_sessions",
                column: "digest",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_share_sessions_expires_at_utc",
                table: "share_sessions",
                column: "expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_share_sessions_tenant_id_share_id",
                table: "share_sessions",
                columns: new[] { "tenant_id", "share_id" });

            migrationBuilder.CreateIndex(
                name: "IX_shares_tenant_id_album_id",
                table: "shares",
                columns: new[] { "tenant_id", "album_id" });

            migrationBuilder.CreateIndex(
                name: "IX_shares_token_hash",
                table: "shares",
                column: "token_hash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_tags_tenant_id_normalized_name",
                table: "tags",
                columns: new[] { "tenant_id", "normalized_name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_tenant_memberships_user_id",
                table: "tenant_memberships",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_tenants_slug",
                table: "tenants",
                column: "slug",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_trash_entries_tenant_id_purge_at_utc",
                table: "trash_entries",
                columns: new[] { "tenant_id", "purge_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_actor_id",
                table: "upload_sessions",
                column: "actor_id");

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_expires_at_utc",
                table: "upload_sessions",
                column: "expires_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_upload_sessions_tenant_id_actor_id_state",
                table: "upload_sessions",
                columns: new[] { "tenant_id", "actor_id", "state" });

            migrationBuilder.CreateIndex(
                name: "IX_users_normalized_email",
                table: "users",
                column: "normalized_email",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_album_items_albums_tenant_id_album_id",
                table: "album_items",
                columns: new[] { "tenant_id", "album_id" },
                principalTable: "albums",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_album_items_assets_tenant_id_asset_id",
                table: "album_items",
                columns: new[] { "tenant_id", "asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" });

            migrationBuilder.AddForeignKey(
                name: "FK_albums_assets_tenant_id_cover_asset_id",
                table: "albums",
                columns: new[] { "tenant_id", "cover_asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_asset_favorites_assets_tenant_id_asset_id",
                table: "asset_favorites",
                columns: new[] { "tenant_id", "asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_asset_lifecycles_assets_tenant_id_asset_id",
                table: "asset_lifecycles",
                columns: new[] { "tenant_id", "asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_asset_metadata_history_assets_tenant_id_asset_id",
                table: "asset_metadata_history",
                columns: new[] { "tenant_id", "asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_asset_revisions_assets_tenant_id_asset_id",
                table: "asset_revisions",
                columns: new[] { "tenant_id", "asset_id" },
                principalTable: "assets",
                principalColumns: new[] { "tenant_id", "id" },
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "album_items");

            migrationBuilder.DropTable(
                name: "api_keys");

            migrationBuilder.DropTable(
                name: "asset_favorites");

            migrationBuilder.DropTable(
                name: "asset_metadata_history");

            migrationBuilder.DropTable(
                name: "asset_tags");

            migrationBuilder.DropTable(
                name: "auth_sessions");

            migrationBuilder.DropTable(
                name: "deletion_tombstones");

            migrationBuilder.DropTable(
                name: "external_identities");

            migrationBuilder.DropTable(
                name: "idempotency_requests");

            migrationBuilder.DropTable(
                name: "local_identities");

            migrationBuilder.DropTable(
                name: "purge_batch_items");

            migrationBuilder.DropTable(
                name: "quota_reservations");

            migrationBuilder.DropTable(
                name: "relationship_snapshots");

            migrationBuilder.DropTable(
                name: "resource_grants");

            migrationBuilder.DropTable(
                name: "retention_holds");

            migrationBuilder.DropTable(
                name: "revoked_tokens");

            migrationBuilder.DropTable(
                name: "share_assets");

            migrationBuilder.DropTable(
                name: "share_sessions");

            migrationBuilder.DropTable(
                name: "tenant_memberships");

            migrationBuilder.DropTable(
                name: "trash_entries");

            migrationBuilder.DropTable(
                name: "upload_parts");

            migrationBuilder.DropTable(
                name: "tags");

            migrationBuilder.DropTable(
                name: "purge_batches");

            migrationBuilder.DropTable(
                name: "shares");

            migrationBuilder.DropTable(
                name: "asset_lifecycles");

            migrationBuilder.DropTable(
                name: "upload_sessions");

            migrationBuilder.DropTable(
                name: "albums");

            migrationBuilder.DropTable(
                name: "assets");

            migrationBuilder.DropTable(
                name: "asset_revisions");

            migrationBuilder.DropTable(
                name: "users");

            migrationBuilder.DropTable(
                name: "blobs");

            migrationBuilder.DropTable(
                name: "tenants");
        }
    }
}
