// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Sqlite.Migrations
{
    /// <inheritdoc />
    public partial class ReconcileLegacyUploadJobQuota : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TEMP TABLE legacy_upload_job_decisions AS
                WITH policy_documents AS (
                    SELECT
                        tenant.id AS tenant_id,
                        tenant.quotas_json,
                        CASE
                            WHEN json_valid(tenant.quotas_json) = 1 AND
                                 json_type(tenant.quotas_json) = 'object'
                                THEN 1
                            ELSE 0
                        END AS valid_document
                    FROM tenants AS tenant
                ),
                policy_values AS (
                    SELECT
                        tenant_id,
                        valid_document,
                        CASE
                            WHEN valid_document = 0 THEN 0
                            WHEN json_type(quotas_json, '$.queuedJobs')
                                 IS NOT NULL THEN 1
                            WHEN json_type(quotas_json, '$.jobs')
                                 IS NOT NULL THEN 1
                            ELSE 0
                        END AS has_limit,
                        CASE
                            WHEN valid_document = 0 THEN NULL
                            WHEN json_type(quotas_json, '$.queuedJobs')
                                 IS NOT NULL
                                THEN json_type(
                                    quotas_json,
                                    '$.queuedJobs')
                            WHEN json_type(quotas_json, '$.jobs')
                                 IS NOT NULL
                                THEN json_type(quotas_json, '$.jobs')
                            ELSE NULL
                        END AS limit_type,
                        CASE
                            WHEN valid_document = 0 THEN NULL
                            WHEN json_type(quotas_json, '$.queuedJobs')
                                 IS NOT NULL
                                THEN json_extract(
                                    quotas_json,
                                    '$.queuedJobs')
                            WHEN json_type(quotas_json, '$.jobs')
                                 IS NOT NULL
                                THEN json_extract(quotas_json, '$.jobs')
                            ELSE NULL
                        END AS limit_value
                    FROM policy_documents
                ),
                tenant_policies AS (
                    SELECT
                        tenant_id,
                        CASE
                            WHEN valid_document = 0 THEN 0
                            WHEN has_limit = 0 THEN 1
                            WHEN limit_type = 'integer' AND
                                 limit_value >= 0 THEN 1
                            ELSE 0
                        END AS valid_policy,
                        CASE
                            WHEN has_limit = 1 AND
                                 limit_type = 'integer' AND
                                 limit_value >= 0
                                THEN limit_value
                            ELSE NULL
                        END AS maximum_jobs
                    FROM policy_values
                ),
                tenant_jobs AS (
                    SELECT
                        tenant.id AS tenant_id,
                        MAX(
                            COALESCE(SUM(CASE
                                WHEN reservation.state IN (
                                    'Reserved',
                                    'Consumed')
                                    THEN reservation.reserved_jobs
                                ELSE 0
                            END), 0),
                            COALESCE(MAX(
                                usage.committed_jobs +
                                usage.reserved_jobs), 0)) AS existing_jobs
                    FROM tenants AS tenant
                    LEFT JOIN quota_reservations AS reservation
                      ON reservation.tenant_id = tenant.id
                    LEFT JOIN quota_usage AS usage
                      ON usage.tenant_id = tenant.id
                    GROUP BY tenant.id
                ),
                candidates AS (
                    SELECT
                        reservation.id AS reservation_id,
                        reservation.tenant_id,
                        ROW_NUMBER() OVER (
                            PARTITION BY reservation.tenant_id
                            ORDER BY upload.created_at_utc, upload.id) AS rank
                    FROM quota_reservations AS reservation
                    JOIN upload_sessions AS upload
                      ON upload.tenant_id = reservation.tenant_id
                     AND upload.id = reservation.upload_session_id
                    WHERE reservation.state = 'Reserved'
                      AND reservation.reserved_jobs = 0
                      AND upload.state IN (
                          'Pending',
                          'UploadIssued',
                          'Committing',
                          'CommitRequested',
                          'Verifying',
                          'Promoting',
                          'Aborting',
                          'OutcomeUnknown',
                          'Reconciling')
                )
                SELECT
                    candidate.reservation_id,
                    candidate.tenant_id,
                    CASE
                        WHEN policy.valid_policy = 1 AND (
                            policy.maximum_jobs IS NULL OR
                            jobs.existing_jobs + (5 * candidate.rank) <=
                                policy.maximum_jobs)
                            THEN 1
                        ELSE 0
                    END AS keep_session
                FROM candidates AS candidate
                JOIN tenant_policies AS policy
                  ON policy.tenant_id = candidate.tenant_id
                JOIN tenant_jobs AS jobs
                  ON jobs.tenant_id = candidate.tenant_id;

                UPDATE quota_reservations
                SET
                    reserved_jobs = 5,
                    version = version + 1
                WHERE id IN (
                    SELECT reservation_id
                    FROM legacy_upload_job_decisions
                    WHERE keep_session = 1);

                UPDATE quota_reservations
                SET
                    state = 'Expired',
                    version = version + 1
                WHERE id IN (
                    SELECT reservation_id
                    FROM legacy_upload_job_decisions
                    WHERE keep_session = 0);

                UPDATE upload_sessions AS upload
                SET
                    last_known_state = CASE
                        WHEN upload.strategy = 'Multipart' AND
                             upload.provider_upload_id IS NOT NULL
                            THEN 'Aborting'
                        ELSE COALESCE(
                            upload.last_known_state,
                            upload.state)
                    END,
                    state = CASE
                        WHEN upload.strategy = 'Multipart' AND
                             upload.provider_upload_id IS NOT NULL
                            THEN 'OutcomeUnknown'
                        ELSE 'Expired'
                    END,
                    version = version + 1
                WHERE EXISTS (
                    SELECT 1
                    FROM quota_reservations AS reservation
                    JOIN legacy_upload_job_decisions AS decision
                      ON decision.reservation_id = reservation.id
                     AND decision.keep_session = 0
                    WHERE reservation.tenant_id = upload.tenant_id
                      AND reservation.upload_session_id = upload.id);

                UPDATE quota_usage
                SET
                    committed_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    reserved_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = quota_usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    version = version + 1;

                INSERT INTO quota_usage (
                    tenant_id,
                    committed_uploads,
                    committed_bytes,
                    committed_objects,
                    committed_compute_units,
                    committed_jobs,
                    committed_budget_units,
                    reserved_uploads,
                    reserved_bytes,
                    reserved_objects,
                    reserved_compute_units,
                    reserved_jobs,
                    reserved_budget_units,
                    version)
                SELECT
                    reservation.tenant_id,
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_uploads ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_objects ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_budget_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_uploads ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_objects ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_budget_units ELSE 0 END),
                    1
                FROM quota_reservations AS reservation
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM quota_usage AS usage
                    WHERE usage.tenant_id = reservation.tenant_id)
                GROUP BY reservation.tenant_id;

                DROP TABLE legacy_upload_job_decisions;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reconciled quota accounting remains valid under the preceding schema.
        }
    }
}
