<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Vistara.Api/Vistara.Api.csproj" />
    <ProjectReference Include="../../src/Vistara.Worker/Vistara.Worker.csproj" />
  </ItemGroup>
</Project>
