// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Postgres.Migrations
{
    /// <inheritdoc />
    public partial class AddWorkerTenantCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "worker_tenant_catalog",
                columns: table => new
                {
                    routed_tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    worker_enabled = table.Column<bool>(type: "boolean", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_worker_tenant_catalog", x => x.routed_tenant_id);
                    table.CheckConstraint("ck_worker_tenant_catalog_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_worker_tenant_catalog_tenants_routed_tenant_id",
                        column: x => x.routed_tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            PostgresTenantRowSecurity.BeginDataMigration(
                migrationBuilder,
                "20260830044748",
                ["tenants"]);

            migrationBuilder.Sql(
                """
                INSERT INTO worker_tenant_catalog (
                    routed_tenant_id,
                    worker_enabled,
                    updated_at_utc,
                    version)
                SELECT
                    tenant.id,
                    tenant.status = 'Active',
                    tenant.updated_at_utc,
                    tenant.version
                FROM tenants AS tenant;
                """);

            PostgresTenantRowSecurity.EndDataMigration(
                migrationBuilder,
                "20260830044748",
                ["tenants"]);

            migrationBuilder.CreateIndex(
                name: "IX_worker_tenant_catalog_worker_enabled_routed_tenant_id",
                table: "worker_tenant_catalog",
                columns: new[] { "worker_enabled", "routed_tenant_id" });

            migrationBuilder.Sql(
                """
                DO $vistara$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM pg_catalog.pg_roles
                        WHERE rolname = 'vistara_worker')
                    THEN
                        GRANT SELECT ON TABLE "worker_tenant_catalog" TO "vistara_worker";
                    END IF;
                END
                $vistara$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "worker_tenant_catalog");
        }
    }
}
