// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Postgres.Migrations
{
    /// <inheritdoc />
    public partial class CompleteRuntimeAndUploadReconciliation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "ck_upload_sessions_state",
                table: "upload_sessions");

            migrationBuilder.AddColumn<long>(
                name: "multipart_part_plan_lifetime_ticks",
                table: "upload_sessions",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "multipart_provider_state",
                table: "upload_sessions",
                type: "character varying(8192)",
                maxLength: 8192,
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "reconciliation_lease_expires_at_utc",
                table: "upload_sessions",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "reconciliation_lease_token",
                table: "upload_sessions",
                type: "character varying(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "authentication_routes",
                columns: table => new
                {
                    lookup_digest = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    kind = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    routed_tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    principal_id = table.Column<Guid>(type: "uuid", nullable: false),
                    credential_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authentication_routes", x => x.lookup_digest);
                    table.CheckConstraint("ck_authentication_routes_kind", "\"kind\" IN ('ApiKey','CookieSession','DeliveryGrant')");
                });

            migrationBuilder.CreateTable(
                name: "cookie_sessions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    session_token_digest = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    antiforgery_token_digest = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    role = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    user_version = table.Column<long>(type: "bigint", nullable: false),
                    membership_version = table.Column<long>(type: "bigint", nullable: false),
                    issued_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    last_seen_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    idle_expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    absolute_expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    revoked_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cookie_sessions", x => x.id);
                    table.UniqueConstraint("AK_cookie_sessions_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_cookie_sessions_expiry", "\"last_seen_at_utc\" >= \"issued_at_utc\" AND \"idle_expires_at_utc\" > \"last_seen_at_utc\" AND \"absolute_expires_at_utc\" > \"issued_at_utc\" AND \"idle_expires_at_utc\" <= \"absolute_expires_at_utc\"");
                    table.CheckConstraint("ck_cookie_sessions_role", "\"role\" IN ('TenantOwner','TenantAdmin','Member','Viewer')");
                    table.CheckConstraint("ck_cookie_sessions_versions", "\"user_version\" >= 1 AND \"membership_version\" >= 1 AND \"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_cookie_sessions_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_cookie_sessions_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "delivery_grants",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_id = table.Column<Guid>(type: "uuid", nullable: true),
                    share_id = table.Column<Guid>(type: "uuid", nullable: true),
                    share_version = table.Column<long>(type: "bigint", nullable: true),
                    asset_id = table.Column<Guid>(type: "uuid", nullable: false),
                    revision_id = table.Column<Guid>(type: "uuid", nullable: false),
                    rendition_kind = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    rendition_identifier = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    permission = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    issued_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    not_before_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    pepper_version_id = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    token_digest_hex = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    revoked_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_delivery_grants", x => x.id);
                    table.UniqueConstraint("AK_delivery_grants_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_delivery_grants_identity", "\"subject_id\" IS NOT NULL OR \"share_id\" IS NOT NULL");
                    table.CheckConstraint("ck_delivery_grants_share", "(\"share_id\" IS NULL AND \"share_version\" IS NULL) OR (\"share_id\" IS NOT NULL AND \"share_version\" >= 1)");
                    table.CheckConstraint("ck_delivery_grants_times", "\"expires_at_utc\" > \"not_before_utc\" AND \"not_before_utc\" >= \"issued_at_utc\"");
                    table.CheckConstraint("ck_delivery_grants_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_delivery_grants_asset_revisions_tenant_id_revision_id",
                        columns: x => new { x.tenant_id, x.revision_id },
                        principalTable: "asset_revisions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_delivery_grants_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_delivery_grants_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "derivative_requests",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    asset_id = table.Column<Guid>(type: "uuid", nullable: false),
                    revision_id = table.Column<Guid>(type: "uuid", nullable: false),
                    job_id = table.Column<Guid>(type: "uuid", nullable: false),
                    idempotency_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    request_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    preset_name = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    preset_revision = table.Column<int>(type: "integer", nullable: false),
                    width = table.Column<int>(type: "integer", nullable: false),
                    height = table.Column<int>(type: "integer", nullable: false),
                    fit = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    format = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    quality = table.Column<int>(type: "integer", nullable: false),
                    focal_point_x = table.Column<decimal>(type: "numeric", nullable: true),
                    focal_point_y = table.Column<decimal>(type: "numeric", nullable: true),
                    crop_x = table.Column<decimal>(type: "numeric", nullable: true),
                    crop_y = table.Column<decimal>(type: "numeric", nullable: true),
                    crop_width = table.Column<decimal>(type: "numeric", nullable: true),
                    crop_height = table.Column<decimal>(type: "numeric", nullable: true),
                    pipeline_id = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    pipeline_fingerprint = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    source_sha256 = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    recipe_sha256 = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    generation_identity = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    cache_key = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    extension = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    is_public = table.Column<bool>(type: "boolean", nullable: false),
                    state = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    failure_code = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    representation_storage_key = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    representation_content_length = table.Column<long>(type: "bigint", nullable: true),
                    representation_content_type = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    representation_sha256 = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_derivative_requests", x => x.id);
                    table.UniqueConstraint("AK_derivative_requests_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_derivative_requests_dimensions", "\"width\" > 0 AND \"height\" > 0");
                    table.CheckConstraint("ck_derivative_requests_quality", "\"quality\" BETWEEN 1 AND 100");
                    table.CheckConstraint("ck_derivative_requests_ready", "(\"state\" <> 'Ready') OR (\"representation_storage_key\" IS NOT NULL AND \"representation_content_length\" > 0 AND \"representation_content_type\" IS NOT NULL AND \"representation_sha256\" IS NOT NULL)");
                    table.CheckConstraint("ck_derivative_requests_state", "\"state\" IN ('Queued','Processing','Ready','Failed')");
                    table.CheckConstraint("ck_derivative_requests_version", "\"version\" >= 1");
                    table.ForeignKey(
                        name: "FK_derivative_requests_asset_revisions_tenant_id_revision_id",
                        columns: x => new { x.tenant_id, x.revision_id },
                        principalTable: "asset_revisions",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_derivative_requests_assets_tenant_id_asset_id",
                        columns: x => new { x.tenant_id, x.asset_id },
                        principalTable: "assets",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_derivative_requests_jobs_job_id",
                        column: x => x.job_id,
                        principalTable: "jobs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_derivative_requests_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "public_derivative_routes",
                columns: table => new
                {
                    lookup_digest = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    routed_tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    request_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_public_derivative_routes", x => x.lookup_digest);
                });

            migrationBuilder.CreateTable(
                name: "rate_limit_windows",
                columns: table => new
                {
                    key_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    window_started_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    request_count = table.Column<int>(type: "integer", nullable: false),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_rate_limit_windows", x => x.key_hash);
                    table.CheckConstraint("ck_rate_limit_windows_count", "\"request_count\" > 0");
                    table.CheckConstraint("ck_rate_limit_windows_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "upload_reconciliation_checkpoints",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    run_id = table.Column<Guid>(type: "uuid", nullable: false),
                    cursor = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_upload_reconciliation_checkpoints", x => new { x.tenant_id, x.run_id });
                    table.ForeignKey(
                        name: "FK_upload_reconciliation_checkpoints_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.AddCheckConstraint(
                name: "ck_upload_sessions_multipart_part_plan_lifetime",
                table: "upload_sessions",
                sql: "\"multipart_part_plan_lifetime_ticks\" IS NULL OR \"multipart_part_plan_lifetime_ticks\" > 0");

            migrationBuilder.AddCheckConstraint(
                name: "ck_upload_sessions_state",
                table: "upload_sessions",
                sql: "\"state\" IN ('Pending','UploadIssued','Committing','CommitRequested','Verifying','Promoting','Accepted','Aborting','Aborted','Expired','Rejected','OutcomeUnknown','Reconciling')");

            migrationBuilder.CreateIndex(
                name: "IX_authentication_routes_kind_credential_id",
                table: "authentication_routes",
                columns: new[] { "kind", "credential_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_authentication_routes_kind_principal_id",
                table: "authentication_routes",
                columns: new[] { "kind", "principal_id" });

            migrationBuilder.CreateIndex(
                name: "IX_cookie_sessions_tenant_id_session_token_digest",
                table: "cookie_sessions",
                columns: new[] { "tenant_id", "session_token_digest" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_cookie_sessions_tenant_id_user_id",
                table: "cookie_sessions",
                columns: new[] { "tenant_id", "user_id" });

            migrationBuilder.CreateIndex(
                name: "IX_cookie_sessions_user_id",
                table: "cookie_sessions",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "IX_delivery_grants_tenant_id_asset_id_revision_id",
                table: "delivery_grants",
                columns: new[] { "tenant_id", "asset_id", "revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_delivery_grants_tenant_id_expires_at_utc",
                table: "delivery_grants",
                columns: new[] { "tenant_id", "expires_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_delivery_grants_tenant_id_revision_id",
                table: "delivery_grants",
                columns: new[] { "tenant_id", "revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_job_id",
                table: "derivative_requests",
                column: "job_id");

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_tenant_id_asset_id_created_at_utc",
                table: "derivative_requests",
                columns: new[] { "tenant_id", "asset_id", "created_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_tenant_id_asset_id_idempotency_key",
                table: "derivative_requests",
                columns: new[] { "tenant_id", "asset_id", "idempotency_key" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_tenant_id_generation_identity",
                table: "derivative_requests",
                columns: new[] { "tenant_id", "generation_identity" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_tenant_id_pipeline_id_source_sha256_rec~",
                table: "derivative_requests",
                columns: new[] { "tenant_id", "pipeline_id", "source_sha256", "recipe_sha256", "extension" });

            migrationBuilder.CreateIndex(
                name: "IX_derivative_requests_tenant_id_revision_id",
                table: "derivative_requests",
                columns: new[] { "tenant_id", "revision_id" });

            migrationBuilder.CreateIndex(
                name: "IX_public_derivative_routes_routed_tenant_id_request_id",
                table: "public_derivative_routes",
                columns: new[] { "routed_tenant_id", "request_id" },
                unique: true);

            PostgresTenantRowSecurity.Enable(
                migrationBuilder,
                [
                    "cookie_sessions",
                    "delivery_grants",
                    "derivative_requests",
                    "upload_reconciliation_checkpoints",
                ]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "authentication_routes");

            migrationBuilder.DropTable(
                name: "cookie_sessions");

            migrationBuilder.DropTable(
                name: "delivery_grants");

            migrationBuilder.DropTable(
                name: "derivative_requests");

            migrationBuilder.DropTable(
                name: "public_derivative_routes");

            migrationBuilder.DropTable(
                name: "rate_limit_windows");

            migrationBuilder.DropTable(
                name: "upload_reconciliation_checkpoints");

            migrationBuilder.DropCheckConstraint(
                name: "ck_upload_sessions_multipart_part_plan_lifetime",
                table: "upload_sessions");

            migrationBuilder.DropCheckConstraint(
                name: "ck_upload_sessions_state",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_part_plan_lifetime_ticks",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "multipart_provider_state",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "reconciliation_lease_expires_at_utc",
                table: "upload_sessions");

            migrationBuilder.DropColumn(
                name: "reconciliation_lease_token",
                table: "upload_sessions");

            migrationBuilder.AddCheckConstraint(
                name: "ck_upload_sessions_state",
                table: "upload_sessions",
                sql: "\"state\" IN ('Pending','UploadIssued','CommitRequested','Verifying','Promoting','Accepted','Aborted','Expired','Rejected','OutcomeUnknown','Reconciling')");
        }
    }
}
