// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Postgres.Migrations
{
    /// <inheritdoc />
    public partial class AddSharingPersistence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "sharing_idempotency",
                columns: table => new
                {
                    key_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    request_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    share_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_sharing_idempotency", x => x.key_hash);
                });

            migrationBuilder.CreateTable(
                name: "sharing_rate_limits",
                columns: table => new
                {
                    key_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    window_started_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    request_count = table.Column<int>(type: "integer", nullable: false),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_sharing_rate_limits", x => x.key_hash);
                    table.CheckConstraint("ck_sharing_rate_limits_count", "\"request_count\" > 0");
                    table.CheckConstraint("ck_sharing_rate_limits_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "sharing_shares",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by_actor_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    target_type = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    album_id = table.Column<Guid>(type: "uuid", nullable: true),
                    assets_json = table.Column<string>(type: "text", nullable: false),
                    permissions = table.Column<int>(type: "integer", nullable: false),
                    metadata_exposure = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    pepper_version_id = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    token_digest_hex = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    password_hash = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    revoked_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    revoked_by_actor_id = table.Column<Guid>(type: "uuid", nullable: true),
                    version = table.Column<long>(type: "bigint", nullable: false),
                    request_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_sharing_shares", x => x.id);
                    table.UniqueConstraint("AK_sharing_shares_tenant_id_id", x => new { x.tenant_id, x.id });
                    table.CheckConstraint("ck_sharing_shares_permissions", "(\"permissions\" & 1) = 1 AND \"permissions\" BETWEEN 1 AND 7");
                    table.CheckConstraint("ck_sharing_shares_version", "\"version\" >= 1");
                });

            migrationBuilder.CreateTable(
                name: "sharing_sessions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    share_id = table.Column<Guid>(type: "uuid", nullable: false),
                    share_version = table.Column<long>(type: "bigint", nullable: false),
                    pepper_version_id = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    digest_hex = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_sharing_sessions", x => x.id);
                    table.CheckConstraint("ck_sharing_sessions_version", "\"share_version\" >= 1");
                    table.ForeignKey(
                        name: "FK_sharing_sessions_sharing_shares_tenant_id_share_id",
                        columns: x => new { x.tenant_id, x.share_id },
                        principalTable: "sharing_shares",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_sharing_sessions_pepper_version_id_digest_hex",
                table: "sharing_sessions",
                columns: new[] { "pepper_version_id", "digest_hex" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_sharing_sessions_tenant_id_expires_at_utc",
                table: "sharing_sessions",
                columns: new[] { "tenant_id", "expires_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_sharing_sessions_tenant_id_share_id",
                table: "sharing_sessions",
                columns: new[] { "tenant_id", "share_id" });

            migrationBuilder.CreateIndex(
                name: "IX_sharing_shares_pepper_version_id_token_digest_hex",
                table: "sharing_shares",
                columns: new[] { "pepper_version_id", "token_digest_hex" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_sharing_shares_tenant_id_created_at_utc_id",
                table: "sharing_shares",
                columns: new[] { "tenant_id", "created_at_utc", "id" });

            migrationBuilder.CreateIndex(
                name: "IX_sharing_shares_tenant_id_expires_at_utc",
                table: "sharing_shares",
                columns: new[] { "tenant_id", "expires_at_utc" });

            migrationBuilder.CreateIndex(
                name: "IX_sharing_shares_tenant_id_revoked_at_utc",
                table: "sharing_shares",
                columns: new[] { "tenant_id", "revoked_at_utc" });

            PostgresTenantRowSecurity.Enable(
                migrationBuilder,
                [
                    "sharing_sessions",
                    "sharing_shares",
                ]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "sharing_idempotency");

            migrationBuilder.DropTable(
                name: "sharing_rate_limits");

            migrationBuilder.DropTable(
                name: "sharing_sessions");

            migrationBuilder.DropTable(
                name: "sharing_shares");
        }
    }
}
