// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vistara.Migrations.Postgres.Migrations
{
    /// <inheritdoc />
    public partial class ReconcileLegacyUploadJobQuota : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            PostgresTenantRowSecurity.BeginDataMigration(
                migrationBuilder,
                "20260829183622",
                [
                    "quota_reservations",
                    "quota_usage",
                    "tenants",
                    "upload_sessions",
                ]);

            migrationBuilder.Sql(
                """
                CREATE TEMP TABLE legacy_upload_job_decisions ON COMMIT DROP AS
                WITH policy_documents AS (
                    SELECT
                        tenant.id AS tenant_id,
                        CASE
                            WHEN tenant.quotas_json IS JSON OBJECT
                                THEN tenant.quotas_json::jsonb
                            ELSE NULL
                        END AS document
                    FROM tenants AS tenant
                ),
                policy_values AS (
                    SELECT
                        tenant_id,
                        document,
                        CASE
                            WHEN document ? 'queuedJobs'
                                THEN document -> 'queuedJobs'
                            WHEN document ? 'jobs'
                                THEN document -> 'jobs'
                            ELSE NULL
                        END AS limit_json,
                        CASE
                            WHEN document ? 'queuedJobs'
                                THEN document ->> 'queuedJobs'
                            WHEN document ? 'jobs'
                                THEN document ->> 'jobs'
                            ELSE NULL
                        END AS limit_text
                    FROM policy_documents
                ),
                validated_policies AS (
                    SELECT
                        tenant_id,
                        document,
                        limit_json,
                        limit_text,
                        CASE
                            WHEN document IS NULL THEN FALSE
                            WHEN limit_json IS NULL THEN TRUE
                            WHEN jsonb_typeof(limit_json) <> 'number'
                                THEN FALSE
                            WHEN limit_text !~
                                 '^(0|[1-9][0-9]{0,18})$'
                                THEN FALSE
                            WHEN length(limit_text) < 19 THEN TRUE
                            ELSE limit_text <= '9223372036854775807'
                        END AS valid_policy
                    FROM policy_values
                ),
                tenant_policies AS (
                    SELECT
                        tenant_id,
                        valid_policy,
                        CASE
                            WHEN valid_policy AND limit_json IS NOT NULL
                                THEN limit_text::bigint
                            ELSE NULL
                        END AS maximum_jobs
                    FROM validated_policies
                ),
                tenant_jobs AS (
                    SELECT
                        tenant.id AS tenant_id,
                        GREATEST(
                            COALESCE(SUM(CASE
                                WHEN reservation.state IN (
                                    'Reserved',
                                    'Consumed')
                                    THEN reservation.reserved_jobs
                                ELSE 0
                            END), 0),
                            COALESCE(MAX(
                                usage.committed_jobs +
                                usage.reserved_jobs), 0)) AS existing_jobs
                    FROM tenants AS tenant
                    LEFT JOIN quota_reservations AS reservation
                      ON reservation.tenant_id = tenant.id
                    LEFT JOIN quota_usage AS usage
                      ON usage.tenant_id = tenant.id
                    GROUP BY tenant.id
                ),
                candidates AS (
                    SELECT
                        reservation.id AS reservation_id,
                        reservation.tenant_id,
                        ROW_NUMBER() OVER (
                            PARTITION BY reservation.tenant_id
                            ORDER BY upload.created_at_utc, upload.id) AS rank
                    FROM quota_reservations AS reservation
                    JOIN upload_sessions AS upload
                      ON upload.tenant_id = reservation.tenant_id
                     AND upload.id = reservation.upload_session_id
                    WHERE reservation.state = 'Reserved'
                      AND reservation.reserved_jobs = 0
                      AND upload.state IN (
                          'Pending',
                          'UploadIssued',
                          'Committing',
                          'CommitRequested',
                          'Verifying',
                          'Promoting',
                          'Aborting',
                          'OutcomeUnknown',
                          'Reconciling')
                )
                SELECT
                    candidate.reservation_id,
                    candidate.tenant_id,
                    CASE
                        WHEN policy.valid_policy AND (
                            policy.maximum_jobs IS NULL OR
                            jobs.existing_jobs + (5 * candidate.rank) <=
                                policy.maximum_jobs)
                            THEN TRUE
                        ELSE FALSE
                    END AS keep_session
                FROM candidates AS candidate
                JOIN tenant_policies AS policy
                  ON policy.tenant_id = candidate.tenant_id
                JOIN tenant_jobs AS jobs
                  ON jobs.tenant_id = candidate.tenant_id;

                UPDATE quota_reservations AS reservation
                SET
                    reserved_jobs = 5,
                    version = reservation.version + 1
                FROM legacy_upload_job_decisions AS decision
                WHERE decision.reservation_id = reservation.id
                  AND decision.keep_session;

                UPDATE quota_reservations AS reservation
                SET
                    state = 'Expired',
                    version = reservation.version + 1
                FROM legacy_upload_job_decisions AS decision
                WHERE decision.reservation_id = reservation.id
                  AND NOT decision.keep_session;

                UPDATE upload_sessions AS upload
                SET
                    last_known_state = CASE
                        WHEN upload.strategy = 'Multipart' AND
                             upload.provider_upload_id IS NOT NULL
                            THEN 'Aborting'
                        ELSE COALESCE(
                            upload.last_known_state,
                            upload.state)
                    END,
                    state = CASE
                        WHEN upload.strategy = 'Multipart' AND
                             upload.provider_upload_id IS NOT NULL
                            THEN 'OutcomeUnknown'
                        ELSE 'Expired'
                    END,
                    version = upload.version + 1
                FROM quota_reservations AS reservation
                JOIN legacy_upload_job_decisions AS decision
                  ON decision.reservation_id = reservation.id
                 AND NOT decision.keep_session
                WHERE reservation.tenant_id = upload.tenant_id
                  AND reservation.upload_session_id = upload.id;

                UPDATE quota_usage AS usage
                SET
                    committed_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    committed_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Consumed'), 0),
                    reserved_uploads = COALESCE((
                        SELECT SUM(reserved_uploads)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_bytes = COALESCE((
                        SELECT SUM(reserved_bytes)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_objects = COALESCE((
                        SELECT SUM(reserved_objects)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_compute_units = COALESCE((
                        SELECT SUM(reserved_compute_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_jobs = COALESCE((
                        SELECT SUM(reserved_jobs)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    reserved_budget_units = COALESCE((
                        SELECT SUM(reserved_budget_units)
                        FROM quota_reservations AS reservation
                        WHERE reservation.tenant_id = usage.tenant_id
                          AND reservation.state = 'Reserved'), 0),
                    version = usage.version + 1;

                INSERT INTO quota_usage (
                    tenant_id,
                    committed_uploads,
                    committed_bytes,
                    committed_objects,
                    committed_compute_units,
                    committed_jobs,
                    committed_budget_units,
                    reserved_uploads,
                    reserved_bytes,
                    reserved_objects,
                    reserved_compute_units,
                    reserved_jobs,
                    reserved_budget_units,
                    version)
                SELECT
                    reservation.tenant_id,
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_uploads ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_objects ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Consumed'
                        THEN reservation.reserved_budget_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_uploads ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_bytes ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_objects ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_compute_units ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_jobs ELSE 0 END),
                    SUM(CASE WHEN reservation.state = 'Reserved'
                        THEN reservation.reserved_budget_units ELSE 0 END),
                    1
                FROM quota_reservations AS reservation
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM quota_usage AS usage
                    WHERE usage.tenant_id = reservation.tenant_id)
                GROUP BY reservation.tenant_id;

                DROP TABLE legacy_upload_job_decisions;
                """);

            PostgresTenantRowSecurity.EndDataMigration(
                migrationBuilder,
                "20260829183622",
                [
                    "quota_reservations",
                    "quota_usage",
                    "tenants",
                    "upload_sessions",
                ]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reconciled quota accounting remains valid under the preceding schema.
        }
    }
}
