// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vistara.Persistence;

#nullable disable

namespace Vistara.Migrations.Postgres.Migrations
{
    [DbContext(typeof(VistaraDbContext))]
    [Migration("20260829000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vistara.Persistence.Model.AlbumItemRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<long>("Position")
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    b.HasKey("TenantId", "AlbumId", "AssetId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "AlbumId", "Position")
                        .IsUnique();

                    b.ToTable("album_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_album_items_position", "\"position\" >= 0");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AlbumRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoverAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_asset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SortMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sort_mode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId", "CoverAssetId");

                    b.HasIndex("TenantId", "OwnerId");

                    b.ToTable("albums", null, t =>
                        {
                            t.HasCheckConstraint("ck_albums_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ApiKeyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digest");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prefix");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<int>("Scopes")
                        .HasColumnType("integer")
                        .HasColumnName("scopes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("TenantId", "OwnerId");

                    b.ToTable("api_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_keys_scopes", "\"scopes\" > 0 AND \"scopes\" <= 15");

                            t.HasCheckConstraint("ck_api_keys_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetFavoriteRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.HasKey("TenantId", "UserId", "AssetId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "AssetId");

                    b.ToTable("asset_favorites", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetLifecycleRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("ActivePurgeBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_purge_batch_id");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.Property<bool>("HasBeenTrashed")
                        .HasColumnType("boolean")
                        .HasColumnName("has_been_trashed");

                    b.Property<DateTime?>("LastRestoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_restored_at_utc");

                    b.Property<Guid?>("LastRestoredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_restored_by_user_id");

                    b.Property<DateTime?>("PurgeEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_evaluated_at_utc");

                    b.Property<bool?>("PurgeHasBlockingReferences")
                        .HasColumnType("boolean")
                        .HasColumnName("purge_has_blocking_references");

                    b.Property<string>("PurgeInitiatorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purge_initiator_kind");

                    b.Property<long?>("PurgeObservedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("purge_observed_revision");

                    b.Property<Guid?>("PurgeRequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("purge_requested_by_user_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "AssetId");

                    b.ToTable("asset_lifecycles", null, t =>
                        {
                            t.HasCheckConstraint("ck_asset_lifecycles_revision", "\"current_revision\" > 0");

                            t.HasCheckConstraint("ck_asset_lifecycles_state", "\"state\" IN ('Ready','Trashed','Purging','Purged')");

                            t.HasCheckConstraint("ck_asset_lifecycles_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetMetadataHistoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changes_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TenantId", "AssetId", "ChangedAtUtc");

                    b.ToTable("asset_metadata_history", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetRevisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetectedContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("detected_content_type");

                    b.Property<string>("DetectedFormat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("detected_format");

                    b.Property<int>("FrameCount")
                        .HasColumnType("integer")
                        .HasColumnName("frame_count");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("PrivateMetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("private_metadata_json");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_number");

                    b.Property<string>("SafeMetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("safe_metadata_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BlobId");

                    b.HasIndex("TenantId", "AssetId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("asset_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_asset_revisions_dimensions", "\"width\" > 0 AND \"height\" > 0");

                            t.HasCheckConstraint("ck_asset_revisions_frames", "\"frame_count\" > 0");

                            t.HasCheckConstraint("ck_asset_revisions_number", "\"revision_number\" > 0");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapturePrecision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capture_precision");

                    b.Property<string>("CaptureSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capture_source");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("CapturedLocal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("captured_local");

                    b.Property<int?>("CapturedOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("captured_offset_minutes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_revision_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId", "CurrentRevisionId");

                    b.HasIndex("TenantId", "OwnerId");

                    b.HasIndex("TenantId", "CreatedAtUtc", "Id");

                    b.ToTable("assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assets_status", "\"status\" IN ('Processing','Ready','Failed','Trashed','Purged')");

                            t.HasCheckConstraint("ck_assets_version", "\"version\" >= 1");

                            t.HasCheckConstraint("ck_assets_visibility", "\"visibility\" IN ('Private','Tenant','Public')");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetTagRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("TenantId", "AssetId", "TagId");

                    b.HasIndex("TenantId", "TagId");

                    b.ToTable("asset_tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_asset_tags_source", "\"source\" IN ('user','import','ai-accepted')");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AuthSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digest");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Digest")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_sessions_expiry", "\"expires_at_utc\" > \"created_at_utc\"");

                            t.HasCheckConstraint("ck_auth_sessions_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.BlobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("container");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderChecksum")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_checksum");

                    b.Property<string>("ProviderVersion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_version");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sha256", "SizeBytes")
                        .IsUnique();

                    b.HasIndex("TenantId", "Provider", "Container", "ObjectKey", "ProviderVersion")
                        .IsUnique();

                    b.ToTable("blobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_blobs_sha256", "length(\"sha256\") = 64");

                            t.HasCheckConstraint("ck_blobs_size", "\"size_bytes\" > 0");

                            t.HasCheckConstraint("ck_blobs_state", "\"state\" IN ('Staging','Quarantined','Active','Deleting','Deleted','Missing')");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.DeletionTombstoneRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("FormerAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("former_asset_id");

                    b.Property<DateTime>("BackupExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("backup_expires_at_utc");

                    b.Property<DateTime>("PurgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at_utc");

                    b.Property<int>("RelationshipCount")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_count");

                    b.Property<string>("RelationshipDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relationship_digest");

                    b.HasKey("TenantId", "FormerAssetId");

                    b.HasIndex("BackupExpiresAtUtc");

                    b.ToTable("deletion_tombstones", null, t =>
                        {
                            t.HasCheckConstraint("ck_deletion_tombstones_backup", "\"backup_expires_at_utc\" >= \"purged_at_utc\"");

                            t.HasCheckConstraint("ck_deletion_tombstones_relationships", "\"relationship_count\" >= 0 AND length(\"relationship_digest\") = 64");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ExternalIdentityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at_utc");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.IdempotencyRequestRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseReference")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("response_reference");

                    b.Property<Guid?>("UploadSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_session_id");

                    b.HasKey("TenantId", "PrincipalId", "Key");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "UploadSessionId")
                        .IsUnique();

                    b.ToTable("idempotency_requests", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.LocalIdentityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at_utc");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_login");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("local_identities", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.PurgeBatchItemRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PurgeBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("purge_batch_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<long>("ReclaimedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("reclaimed_bytes");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TenantId", "PurgeBatchId", "AssetId");

                    b.ToTable("purge_batch_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_purge_batch_items_bytes", "\"reclaimed_bytes\" >= 0");

                            t.HasCheckConstraint("ck_purge_batch_items_result", "\"result\" IN ('Purged','Blocked','Failed')");

                            t.HasCheckConstraint("ck_purge_batch_items_revision", "\"revision\" > 0");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.PurgeBatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_count");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime?>("DryRunCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dry_run_completed_at_utc");

                    b.Property<string>("DryRunHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dry_run_hash");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("integer")
                        .HasColumnName("eligible_count");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "State", "RequestedAtUtc");

                    b.ToTable("purge_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_purge_batches_counts", "\"candidate_count\" >= 0 AND \"eligible_count\" >= 0 AND \"eligible_count\" <= \"candidate_count\"");

                            t.HasCheckConstraint("ck_purge_batches_state", "\"state\" IN ('Draft','DryRunCompleted','Approved','Executing','Completed','Cancelled')");

                            t.HasCheckConstraint("ck_purge_batches_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.QuotaReservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_bytes");

                    b.Property<long>("ReservedComputeUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_compute_units");

                    b.Property<int>("ReservedObjects")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_objects");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UploadSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_session_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "UploadSessionId")
                        .IsUnique();

                    b.ToTable("quota_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_quota_reservations_bytes", "\"reserved_bytes\" > 0");

                            t.HasCheckConstraint("ck_quota_reservations_compute", "\"reserved_compute_units\" >= 0");

                            t.HasCheckConstraint("ck_quota_reservations_objects", "\"reserved_objects\" > 0");

                            t.HasCheckConstraint("ck_quota_reservations_state", "\"state\" IN ('Reserved','Consumed','Released','Expired')");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.RelationshipSnapshotRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.HasKey("TenantId", "AssetId", "Kind", "ResourceId");

                    b.ToTable("relationship_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_relationship_snapshots_kind", "\"kind\" IN ('Album','Tag','Favorite','Share','Grant')");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ResourceGrantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("GranteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grantee_id");

                    b.Property<string>("GranteeKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("grantee_kind");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resource_kind");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ResourceKind", "ResourceId", "GranteeKind", "GranteeId")
                        .IsUnique();

                    b.ToTable("resource_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_resource_grants_grantee_kind", "\"grantee_kind\" IN ('User','Group')");

                            t.HasCheckConstraint("ck_resource_grants_resource_kind", "\"resource_kind\" IN ('Album','Asset')");

                            t.HasCheckConstraint("ck_resource_grants_role", "\"role\" IN ('Viewer','Contributor','Curator')");

                            t.HasCheckConstraint("ck_resource_grants_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.RetentionHoldRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid?>("ReleasedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssetId", "ReleasedAtUtc");

                    b.ToTable("retention_holds", null, t =>
                        {
                            t.HasCheckConstraint("ck_retention_holds_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.RevokedTokenRow", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<string>("Jti")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Issuer", "Jti");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareAssetRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_number");

                    b.HasKey("TenantId", "ShareId", "AssetId");

                    b.HasIndex("TenantId", "AssetId");

                    b.HasIndex("TenantId", "RevisionId");

                    b.ToTable("share_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_assets_revision", "\"revision_number\" > 0");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_kind");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "AlbumId");

                    b.ToTable("shares", null, t =>
                        {
                            t.HasCheckConstraint("ck_shares_permissions", "(\"permissions\" & 1) = 1 AND \"permissions\" >= 1 AND \"permissions\" <= 7");

                            t.HasCheckConstraint("ck_shares_target_kind", "\"target_kind\" IN ('Album','Snapshot')");

                            t.HasCheckConstraint("ck_shares_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digest");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Digest")
                        .IsUnique();

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "ShareId");

                    b.ToTable("share_sessions", (string)null);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TagRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("color");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_tags_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TenantMembershipRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at_utc");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_role", "\"role\" IN ('TenantOwner','TenantAdmin','Member','Viewer')");

                            t.HasCheckConstraint("ck_tenant_memberships_status", "\"status\" IN ('Invited','Active','Suspended','Removed')");

                            t.HasCheckConstraint("ck_tenant_memberships_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TenantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QuotasJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quotas_json");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_identity", "\"id\" = \"tenant_id\"");

                            t.HasCheckConstraint("ck_tenants_status", "\"status\" IN ('Active','Suspended','Deactivated')");

                            t.HasCheckConstraint("ck_tenants_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TrashEntryRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime>("PurgeAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RestorationMetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("restoration_metadata_json");

                    b.HasKey("TenantId", "AssetId");

                    b.HasIndex("TenantId", "PurgeAtUtc");

                    b.ToTable("trash_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_trash_entries_purge_at", "\"purge_at_utc\" > \"deleted_at_utc\"");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.UploadPartRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UploadSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_session_id");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("part_number");

                    b.Property<string>("Checksum")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("checksum");

                    b.Property<string>("EntityTag")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("entity_tag");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("TenantId", "UploadSessionId", "PartNumber");

                    b.ToTable("upload_parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_upload_parts_number", "\"part_number\" > 0");

                            t.HasCheckConstraint("ck_upload_parts_size", "\"size_bytes\" > 0");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.UploadSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeclaredContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("declared_content_type");

                    b.Property<long>("ExpectedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_bytes");

                    b.Property<string>("ExpectedSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("LastKnownState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_known_state");

                    b.Property<string>("ProviderUploadId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("provider_upload_id");

                    b.Property<string>("StagingKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("staging_key");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "ActorId", "State");

                    b.ToTable("upload_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_upload_sessions_expected_bytes", "\"expected_bytes\" > 0");

                            t.HasCheckConstraint("ck_upload_sessions_state", "\"state\" IN ('Pending','UploadIssued','CommitRequested','Verifying','Promoting','Accepted','Aborted','Expired','Rejected','OutcomeUnknown','Reconciling')");

                            t.HasCheckConstraint("ck_upload_sessions_strategy", "\"strategy\" IN ('Proxy','Direct','Multipart')");

                            t.HasCheckConstraint("ck_upload_sessions_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "\"status\" IN ('Active','Suspended','Disabled')");

                            t.HasCheckConstraint("ck_users_version", "\"version\" >= 1");
                        });
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AlbumItemRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AlbumRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AlbumId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AlbumRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CoverAssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ApiKeyRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetFavoriteRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetLifecycleRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithOne()
                        .HasForeignKey("Vistara.Persistence.Model.AssetLifecycleRow", "TenantId", "AssetId")
                        .HasPrincipalKey("Vistara.Persistence.Model.AssetRow", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetMetadataHistoryRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetRevisionRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.BlobRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BlobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AssetRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CurrentRevisionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AssetTagRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.TagRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TagId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.AuthSessionRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.BlobRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.DeletionTombstoneRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ExternalIdentityRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.IdempotencyRequestRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UploadSessionRow", null)
                        .WithOne()
                        .HasForeignKey("Vistara.Persistence.Model.IdempotencyRequestRow", "TenantId", "UploadSessionId")
                        .HasPrincipalKey("Vistara.Persistence.Model.UploadSessionRow", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.LocalIdentityRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.PurgeBatchItemRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.PurgeBatchRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PurgeBatchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.PurgeBatchRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.QuotaReservationRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UploadSessionRow", null)
                        .WithOne()
                        .HasForeignKey("Vistara.Persistence.Model.QuotaReservationRow", "TenantId", "UploadSessionId")
                        .HasPrincipalKey("Vistara.Persistence.Model.UploadSessionRow", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.RelationshipSnapshotRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetLifecycleRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ResourceGrantRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.RetentionHoldRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareAssetRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.AssetRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RevisionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.ShareRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ShareId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AlbumRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AlbumId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vistara.Persistence.Model.ShareSessionRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.ShareRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ShareId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TagRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TenantMembershipRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.TrashEntryRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.AssetLifecycleRow", null)
                        .WithOne()
                        .HasForeignKey("Vistara.Persistence.Model.TrashEntryRow", "TenantId", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.UploadPartRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UploadSessionRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UploadSessionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vistara.Persistence.Model.UploadSessionRow", b =>
                {
                    b.HasOne("Vistara.Persistence.Model.UserRow", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vistara.Persistence.Model.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
