<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Vistara.Domain/Vistara.Domain.csproj" />
    <ProjectReference Include="../../src/Vistara.Application/Vistara.Application.csproj" />
    <ProjectReference Include="../../src/Vistara.Contracts/Vistara.Contracts.csproj" />
    <ProjectReference Include="../../src/Vistara.Persistence/Vistara.Persistence.csproj" />
    <ProjectReference Include="../../src/Vistara.Storage.Local/Vistara.Storage.Local.csproj" />
    <ProjectReference Include="../../src/Vistara.Storage.Azure/Vistara.Storage.Azure.csproj" />
    <ProjectReference Include="../../src/Vistara.Storage.S3/Vistara.Storage.S3.csproj" />
    <ProjectReference Include="../../src/Vistara.Imaging.NetVips/Vistara.Imaging.NetVips.csproj" />
    <ProjectReference Include="../../src/Vistara.Auth/Vistara.Auth.csproj" />
    <ProjectReference Include="../../src/Vistara.Observability/Vistara.Observability.csproj" />
    <ProjectReference Include="../../src/Vistara.Api/Vistara.Api.csproj" />
    <ProjectReference Include="../../src/Vistara.Worker/Vistara.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
