/* global console, process, structuredClone */

import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  compileErrors,
  dereference,
  validate,
} from "@readme/openapi-parser";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const defaultRepositoryRoot = path.resolve(scriptDirectory, "../../..");
const manifestRelativePath =
  "src/Vistara.Api/OpenApi/Gallery/gallery-contract.openapi.json";

const generatedHeader = `// <auto-generated>
// Generated by src/Vistara.Web/scripts/gallery-api.mjs from
// src/Vistara.Api/OpenApi/Gallery/gallery-contract.openapi.json.
// The manifest is a temporary reviewed contract and does not assert runtime routes exist.
// Do not edit this file directly.
// </auto-generated>`;

export async function loadGalleryManifest(
  repositoryRoot = defaultRepositoryRoot,
) {
  const content = await readFile(
    path.join(repositoryRoot, manifestRelativePath),
    "utf8",
  );
  const manifest = JSON.parse(content);
  await validateGalleryManifest(manifest);
  return manifest;
}

export async function validateGalleryManifest(manifest) {
  validateVistaraMetadata(manifest);
  assertLocalReferences(manifest);

  const parserOptions = {
    resolve: {
      external: false,
      file: false,
    },
  };
  const result = await validate(structuredClone(manifest), parserOptions);
  if (!result.valid) {
    throw new Error(compileErrors(result));
  }

  return dereference(structuredClone(manifest), parserOptions);
}

export async function generateGalleryArtifacts(manifest) {
  const dereferencedManifest = await validateGalleryManifest(manifest);
  const canonicalManifest = `${JSON.stringify(manifest, null, 2)}\n`;

  return new Map([
    [
      "src/Vistara.Api/OpenApi/Gallery/GalleryOpenApiCatalog.cs",
      renderCatalog(manifest),
    ],
    [
      "src/Vistara.Api/OpenApi/Gallery/GalleryOpenApiDocument.g.cs",
      renderEmbeddedDocument(canonicalManifest),
    ],
    [
      "src/Vistara.Web/src/api/generated/models.ts",
      renderModels(manifest, dereferencedManifest.components.schemas),
    ],
    [
      "src/Vistara.Web/src/api/generated/client.ts",
      renderClient(manifest),
    ],
    [
      "src/Vistara.Web/src/api/generated/index.ts",
      `${generatedHeader}\n\nexport * from "./client";\nexport * from "./models";\n`,
    ],
  ]);
}

export async function findGeneratedDrift(artifacts, repositoryRoot) {
  const drift = [];
  for (const [relativePath, expected] of artifacts) {
    try {
      const actual = await readFile(path.join(repositoryRoot, relativePath), "utf8");
      if (actual !== expected) {
        drift.push(relativePath);
      }
    } catch (error) {
      if (error?.code !== "ENOENT") {
        throw error;
      }
      drift.push(relativePath);
    }
  }
  return drift;
}

async function writeArtifacts(artifacts, repositoryRoot) {
  for (const [relativePath, content] of artifacts) {
    const target = path.join(repositoryRoot, relativePath);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content);
  }
}

function validateVistaraMetadata(manifest) {
  if (
    manifest?.openapi !== "3.1.0" ||
    manifest["x-vistara-contract-source"] !== "temporary-reviewed-manifest" ||
    manifest["x-vistara-runtime-gallery-routes"] !== false
  ) {
    throw new Error(
      "Gallery manifest must remain an explicit temporary OpenAPI 3.1 contract and must not claim runtime gallery routes exist.",
    );
  }

  let operationCount = 0;
  for (const [, , operation] of operations(manifest)) {
    if (
      typeof operation.operationId !== "string" ||
      operation["x-vistara-client"] === undefined ||
      operation["x-vistara-clr"] === undefined
    ) {
      throw new Error("Every gallery operation must have client and CLR metadata.");
    }
    operationCount += 1;
  }

  if (operationCount === 0) {
    throw new Error("Gallery manifest must contain operations.");
  }
}

function assertLocalReferences(value) {
  if (Array.isArray(value)) {
    for (const item of value) {
      assertLocalReferences(item);
    }
    return;
  }

  if (value === null || typeof value !== "object") {
    return;
  }

  if (
    Object.hasOwn(value, "$ref") &&
    (typeof value.$ref !== "string" || !value.$ref.startsWith("#/"))
  ) {
    throw new Error(
      "Gallery OpenAPI generation only permits local $ref values beginning with '#/'.",
    );
  }

  for (const child of Object.values(value)) {
    assertLocalReferences(child);
  }
}

function* operations(manifest) {
  for (const [route, pathItem] of Object.entries(manifest.paths)) {
    for (const method of ["get", "post", "put", "patch", "delete"]) {
      if (pathItem[method] !== undefined) {
        yield [route, method, pathItem[method]];
      }
    }
  }
}

function renderModels(manifest, schemas) {
  const declarations = [
    ...(manifest["x-vistara-typescript-declarations"] ?? []),
    ...Object.values(schemas).map(
      (schema) => schema["x-vistara-typescript-declaration"],
    ),
  ];
  if (declarations.some((declaration) => typeof declaration !== "string")) {
    throw new Error("Every generated TypeScript schema needs a declaration.");
  }

  return `${generatedHeader}\n\n${declarations.join("\n\n")}\n`;
}

function renderClient(manifest) {
  const methods = [...operations(manifest)]
    .map(([route, method, operation]) =>
      renderClientMethod(route, method, operation),
    )
    .join("\n\n");

  return `${generatedHeader}

import type * as Api from "./models";

export interface ApiClientOptions {
  readonly baseUrl?: string;
  readonly fetch?: typeof fetch;
}

export interface IdempotentMutationOptions {
  readonly idempotencyKey: Api.IdempotencyKey;
}

export interface VersionedMutationOptions extends IdempotentMutationOptions {
  readonly ifMatch: Api.EntityTag;
}

export interface ApiResponse<T> {
  readonly data: T;
  readonly etag?: Api.EntityTag;
}

export class VistaraApiError extends Error {
  public constructor(
    public readonly status: number,
    public readonly problem: Api.ApiProblemDetails,
  ) {
    super(problem.detail ?? problem.title);
    this.name = "VistaraApiError";
  }
}

export class VistaraApiClient {
  readonly #baseUrl: string;
  readonly #fetch: typeof fetch;

  public constructor(options: ApiClientOptions = {}) {
    this.#baseUrl = options.baseUrl?.replace(/\\/+$/, "") ?? "";
    this.#fetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

${indent(methods, 2)}

  async #get<T>(path: string, query?: object): Promise<ApiResponse<T>> {
    return this.#request<T>("GET", appendQuery(path, query));
  }

  async #mutate<T>(
    method: "POST" | "PUT" | "PATCH" | "DELETE",
    path: string,
    body?: unknown,
    options?: IdempotentMutationOptions | VersionedMutationOptions,
  ): Promise<ApiResponse<T>> {
    const headers = new Headers();
    if (options !== undefined) {
      assertIdempotencyKey(options.idempotencyKey);
      headers.set("Idempotency-Key", options.idempotencyKey);
      if ("ifMatch" in options) {
        headers.set("If-Match", options.ifMatch);
      }
    }
    if (body !== undefined) {
      headers.set("Content-Type", "application/json");
    }

    return this.#request<T>(method, path, headers, body);
  }

  async #request<T>(
    method: string,
    path: string,
    headers = new Headers(),
    body?: unknown,
  ): Promise<ApiResponse<T>> {
    const response = await this.#fetch(\`\${this.#baseUrl}\${path}\`, {
      method,
      headers,
      credentials: "same-origin",
      body: body === undefined ? undefined : JSON.stringify(body),
    });

    if (!response.ok) {
      throw new VistaraApiError(
        response.status,
        (await response.json()) as Api.ApiProblemDetails,
      );
    }

    const etag = response.headers.get("ETag") as Api.EntityTag | null;
    const data =
      response.status === 204
        ? (undefined as T)
        : ((await response.json()) as T);
    return etag === null ? { data } : { data, etag };
  }
}

function appendQuery(path: string, query?: object): string {
  if (query === undefined) {
    return path;
  }

  const parameters = new URLSearchParams();
  for (const [name, value] of Object.entries(query)) {
    if (value === undefined || value === null) {
      continue;
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        parameters.append(name, String(item));
      }
      continue;
    }

    parameters.set(name, String(value));
  }

  const encoded = parameters.toString();
  return encoded.length === 0 ? path : \`\${path}?\${encoded}\`;
}

function assertBatchSize(items: readonly unknown[]): void {
  if (items.length < 1 || items.length > 200) {
    throw new RangeError("A batch must contain between 1 and 200 items.");
  }
}

function assertIdempotencyKey(value: string): void {
  if (value.length < 1 || value.length > 255 || /[\\p{Cc}\\s]/u.test(value)) {
    throw new TypeError("The idempotency key is invalid.");
  }
}

function segment(value: string): string {
  return encodeURIComponent(value);
}
`;
}

function renderClientMethod(route, method, operation) {
  const metadata = operation["x-vistara-client"];
  const parameters = [];
  for (const parameter of metadata.pathParameters) {
    parameters.push(`${parameter.name}: ${apiType(parameter.type)}`);
  }
  if (metadata.queryType !== null) {
    parameters.push(`query: ${apiType(metadata.queryType)} = {}`);
  }
  if (metadata.requestType !== null) {
    parameters.push(`request: ${apiType(metadata.requestType)}`);
  }
  if (metadata.options === "versioned") {
    parameters.push("options: VersionedMutationOptions");
  } else if (metadata.options === "idempotent") {
    parameters.push("options: IdempotentMutationOptions");
  }

  const signature =
    parameters.length <= 1
      ? `public ${operation.operationId}(${parameters.join("")}) {`
      : `public ${operation.operationId}(\n${indent(
          `${parameters.join(",\n")},`,
          2,
        )}\n) {`;
  const pathExpression = renderPathExpression(route, metadata.pathParameters);
  const statements = [];
  if (metadata.batchExpression !== null) {
    if (metadata.batchOptional) {
      statements.push(
        `if (${metadata.batchExpression} !== undefined) {\n  assertBatchSize(${metadata.batchExpression});\n}`,
      );
    } else {
      statements.push(`assertBatchSize(${metadata.batchExpression});`);
    }
  }

  if (method === "get") {
    const query = metadata.queryType === null ? "" : ", query";
    statements.push(
      `return this.#get<${apiType(metadata.responseType)}>(${pathExpression}${query});`,
    );
  } else {
    const args = [
      `"${method.toUpperCase()}"`,
      pathExpression,
      metadata.requestType === null ? "undefined" : "request",
    ];
    if (metadata.options !== null) {
      args.push("options");
    } else if (metadata.requestType === null) {
      args.pop();
    }
    statements.push(
      `return this.#mutate<${apiType(metadata.responseType)}>(\n${indent(
        `${args.join(",\n")},`,
        2,
      )}\n);`,
    );
  }

  return `${signature}\n${indent(statements.join("\n"), 2)}\n}`;
}

function renderPathExpression(route, pathParameters) {
  if (pathParameters.length === 0) {
    return JSON.stringify(route);
  }
  let expression = route;
  for (const parameter of pathParameters) {
    expression = expression.replace(
      `{${parameter.templateName}}`,
      `\${segment(${parameter.name})}`,
    );
  }
  return `\`${expression}\``;
}

function apiType(type) {
  if (type === "void") {
    return "void";
  }
  return type.replace(/\b[A-Z][A-Za-z0-9]*\b/gu, (name) => `Api.${name}`);
}

function renderCatalog(manifest) {
  const catalogOperations = [...operations(manifest)]
    .map(([route, method, operation]) => {
      const clr = operation["x-vistara-clr"];
      const requestTypes = clr.requestTypes
        .map((type) => `typeof(${type})`)
        .join(", ");
      const responseType =
        clr.responseType === null ? "null" : `typeof(${clr.responseType})`;
      return `new(
    ${csharpString(operation.operationId)},
    ${csharpString(method.toUpperCase())},
    ${csharpString(route)},
    ${csharpString(operation.summary)},
    ${clr.queryType === null ? "null" : `typeof(${clr.queryType})`},
    [${requestTypes}],
    [new GalleryOpenApiPayload(${clr.responseStatus}, ${responseType})],
    Array.AsReadOnly([${clr.problemStatuses.join(", ")}]),
    RequiredHeaders(${csharpBoolean(clr.requiresIfMatch)}, ${csharpBoolean(clr.requiresIdempotencyKey)}),
    ${csharpBoolean(clr.requiresAuthentication)},
    ${csharpBoolean(clr.requiresIfMatch)},
    ${csharpBoolean(clr.requiresIdempotencyKey)})`;
    })
    .join(",\n");

  const catalogSchemas = manifest["x-vistara-catalog-schemas"]
    .map(
      (schema) => `new(
    ${csharpString(schema.schemaId)},
    typeof(${schema.clrType}),
    ${csharpString(schema.description)})`,
    )
    .join(",\n");

  return `${generatedHeader}

#nullable enable

using System.Collections.ObjectModel;
using Vistara.Contracts.Assets;
using Vistara.Contracts.Concurrency;
using Vistara.Contracts.Errors;
using Vistara.Contracts.Gallery;
using Vistara.Contracts.Idempotency;
using Vistara.Contracts.Lifecycle;
using Vistara.Contracts.Pagination;
using Vistara.Contracts.Sharing;

namespace Vistara.Api.OpenApi.Gallery;

public static class GalleryOpenApiCatalog
{
    private static readonly IReadOnlyDictionary<string, GalleryOpenApiOperation> ById =
        BuildCatalog();

    private static readonly IReadOnlyDictionary<Type, GalleryOpenApiSchema> ByType =
        BuildSchemas();

    public static IReadOnlyCollection<GalleryOpenApiOperation> Operations =>
        new ReadOnlyCollection<GalleryOpenApiOperation>(ById.Values.ToArray());

    public static IReadOnlyCollection<GalleryOpenApiSchema> Schemas =>
        new ReadOnlyCollection<GalleryOpenApiSchema>(ByType.Values.ToArray());

    public static Type ProblemSchema => typeof(ApiProblemDetails);

    public static GalleryOpenApiOperation Get(string operationId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(operationId);
        return ById.TryGetValue(operationId, out GalleryOpenApiOperation? operation)
            ? operation
            : throw new KeyNotFoundException(
                $"Gallery OpenAPI operation '{operationId}' is not registered.");
    }

    public static GalleryOpenApiSchema GetSchema(Type contractType)
    {
        ArgumentNullException.ThrowIfNull(contractType);
        return ByType.TryGetValue(contractType, out GalleryOpenApiSchema? schema)
            ? schema
            : throw new KeyNotFoundException(
                $"Gallery OpenAPI schema for '{contractType.Name}' is not registered.");
    }

    private static ReadOnlyDictionary<string, GalleryOpenApiOperation> BuildCatalog()
    {
        GalleryOpenApiOperation[] operations =
        [
${indent(catalogOperations, 12)},
        ];

        var byId = new Dictionary<string, GalleryOpenApiOperation>(StringComparer.Ordinal);
        foreach (GalleryOpenApiOperation operation in operations)
        {
            byId.Add(operation.OperationId, operation);
        }

        return new ReadOnlyDictionary<string, GalleryOpenApiOperation>(byId);
    }

    private static ReadOnlyDictionary<Type, GalleryOpenApiSchema> BuildSchemas()
    {
        GalleryOpenApiSchema[] schemas =
        [
${indent(catalogSchemas, 12)},
        ];

        return new ReadOnlyDictionary<Type, GalleryOpenApiSchema>(
            schemas.ToDictionary(schema => schema.ClrType));
    }

    private static ReadOnlyDictionary<string, Type> RequiredHeaders(
        bool requiresIfMatch,
        bool requiresIdempotencyKey)
    {
        var headers = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
        if (requiresIfMatch)
        {
            headers.Add("If-Match", typeof(EntityTag));
        }

        if (requiresIdempotencyKey)
        {
            headers.Add("Idempotency-Key", typeof(IdempotencyKey));
        }

        return new ReadOnlyDictionary<string, Type>(headers);
    }
}
`;
}

function renderEmbeddedDocument(canonicalManifest) {
  return `${generatedHeader}

namespace Vistara.Api.OpenApi.Gallery;

public static class GalleryOpenApiDocument
{
    public const string Route = "/openapi/gallery-v1.json";

    public const string Json = """
${canonicalManifest}""";
}
`;
}

function csharpString(value) {
  return JSON.stringify(value);
}

function csharpBoolean(value) {
  return value ? "true" : "false";
}

function indent(value, spaces) {
  const prefix = " ".repeat(spaces);
  return value
    .split("\n")
    .map((line) => (line.length === 0 ? "" : `${prefix}${line}`))
    .join("\n");
}

async function runCli() {
  const command = process.argv[2];
  if (command !== "generate" && command !== "check") {
    console.error("Usage: node scripts/gallery-api.mjs <generate|check>");
    process.exitCode = 2;
    return;
  }

  const manifest = await loadGalleryManifest();
  const artifacts = await generateGalleryArtifacts(manifest);
  if (command === "generate") {
    await writeArtifacts(artifacts, defaultRepositoryRoot);
    console.log(`Generated ${artifacts.size} gallery API artifacts.`);
    return;
  }

  const drift = await findGeneratedDrift(artifacts, defaultRepositoryRoot);
  if (drift.length > 0) {
    console.error("Gallery API generated files are stale or manually edited:");
    for (const relativePath of drift) {
      console.error(`- ${relativePath}`);
    }
    console.error("Run: npm --prefix src/Vistara.Web run api:generate");
    process.exitCode = 1;
    return;
  }

  console.log("Gallery API generated files match the reviewed OpenAPI manifest.");
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  await runCli();
}
